### ISSUE TITLE
Support WHERE IN on multiple columns

### ISSUE THREAD

**Issue by jesenko** [elixir-ecto/ecto#1457]
In postgres it is possible to query all rows from a table that match any of the given n-column values, e.g.,

    select * from tbl
    where (tbl.col_a, tbl.col_b) in (('val1', 1), ('val2', 2), ('val2', 1))

In Ecto (2.0.rc5), there is currently no way to construct such query. Trying to use postgres `any` function with `fragment`,

    from tbl in MyProj.Tbl,
    where: fragment("(?, ?) = any(?)", tbl.col_a, tbl.col_b, ^[{"val1", 1}, {"val2", 2}, {"val2", 1}])
fails with

    ** (FunctionClauseError) no function clause matching in :lists.zip/2

       (postgrex) lib/postgrex/extensions/record.ex:21: Postgrex.Extensions.Record.encode_record/3
       (postgrex) lib/postgrex/extensions/array.ex:54: anonymous fn/3 in Postgrex.Extensions.Array.encode_array/4
       (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (postgrex) lib/postgrex/extensions/array.ex:50: Postgrex.Extensions.Array.encode_array/4
       (postgrex) lib/postgrex/extensions/array.ex:22: Postgrex.Extensions.Array.encode_array/3

See [elixir-ecto mailing list thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/elixir-ecto/FJBAq9raGAc) for reference.

**Comment by mahcloud** [comment]
👍

**Comment by ericmj** [comment]
I don't think we can support this as it is proposed here because Postgrex can only encode records that are defined as proper types. In this case anonymous records are used which we don't have enough type information to encode.

**Comment by josevalim** [comment]
Yes, @ericmj has said it correctly. We can't make it work with tuples as we don't know how to encode them.

**Comment by ericmj** [comment]
Can you show how you did it before?

**Comment by methyl** [comment]
Thanks for swift reply. TBH I didn't, this is my first try, was referring to [this answer on Elixir Forum by OvermindDL1](https://elixirforum.com/t/building-a-dynamic-nested-where-in-query-with-ecto/15580/2).

Right now I have to use raw SQL query with `Ecto.Adapters.SQL.query` which is of course far from optimal (BTW is there a way to manually escape a value for such raw SQL usage?)

Unsafe fragment would make a bit better – I still have to escape manually but at least for most part of the query building I can use Ecto.Query. Is there any other way that I'm missing or any plans to implement? If not, I may be able to dig into that if you could help me to find some starting points.

**Comment by ericmj** [comment]
> Right now I have to use raw SQL query with `Ecto.Adapters.SQL.query` which is of course far from optimal (BTW is there a way to manually escape a value for such raw SQL usage?)

Ecto avoids doing manually escaping because it's fragile and hard to do for every supported type.

> Unsafe fragment would make a bit better – I still have to escape manually but at least for most part of the query building I can use Ecto.Query. Is there any other way that I'm missing or any plans to implement? If not, I may be able to dig into that if you could help me to find some starting points.

There are no plans currently to support it. We would like to support it but right there doesn't seem to do a way to do it with Ecto. Postgres does not give us the necessary type information to encode arbitrary tuples.

**Comment by OvermindDL1** [comment]
> There are no plans currently to support it. We would like to support it but right there doesn't seem to do a way to do it with Ecto. Postgres does not give us the necessary type information to encode arbitrary tuples.

Hence why a new command would be needed to both accept a list of N-Tuples and to define the types of each tuple field.  Such a command would be useful both for `WHERE ... IN ...` as well as for composite foreign key fields among other uses.  That would be a pretty useful base command for a variety of purposes.  Perhaps it's API could be something like (using the name `some_cmd_name` here as purely an example):
```elixir
from s in schema,
  where: {s.a, s.b, s.c} in some_cmd_name(^list_of_tuples, {:integer, :string, MyType})
```
The signature of the types would be the same as the `type` command (perhaps the type command could handle/be `some_cmd_name`?) so you could also do forms such as:
```elixir
from s in schema,
  where: {s.a, s.b, s.c} in some_cmd_name(^list_of_tuples, {s.a, s.b, s.c})
```
Where this latter example could be used internally for the given form of:
```elixir
from s in schema,
  where: {s.a, s.b, s.c} in ^list_of_tuples
```
Which since you know that `{s.a, s.b, s.c}` is given then whatever is on the other side of the operator must be a tuple-like form of the same types as `{s.a, s.b, s.c}` as well, such a list of those tuples for the `in` operator or just a tuple for things like `==`, etc...

Thus the existing `type/2` command could be enhanced to handle this case along with accepting a tuple in the field position as well to act as a default type case when a schema is available.

**Comment by josevalim** [comment]
That's a good point. We could even introduce something as obviously named as `list_of_tuples(arg, type)` but we can't use `type` because you can already pass a tuple as `{:array, :foo}` or `{composite, foo}`.

However, this solves only the Ecto part of things. We would still need a way to pass this list of tuples, with all of the type information, all the way down to Postgrex. It is doable by using a custom postgres type + custom ecto type, but it is not quite trivial.

**Comment by OvermindDL1** [comment]
> but we can't use `type` because you can already pass a tuple as

Ahh true true...

> However, this solves only the Ecto part of things. We would still need a way to pass this list of tuples, with all of the type information, all the way down to Postgrex. It is doable by using a custom postgres type + custom ecto type, but it is not quite trivial.

If it's done then it would open up a lot of functionality that is currently impossible otherwise in Ecto without unsafe_fragment (which I can't find in the docs anymore...) or dropping to raw SQL (which is what I've done for years now since almost all the foreign keys in this database are composite keys, which ecto just kind of breaks with for migrations and have to handle it manually without any of the `*_assoc` helpers in Ecto.Query).

**Comment by ericmj** [comment]
The issue isn't with type information in Ecto, the issue is type information in Postgrex. Postgrex asks the database for type information to know how to encode parameters, but if the database does not give us enough information it is impossible to correctly encode the data. Unfortunately no additional type information in Ecto can solve this problem.

Remember that ecto types are different from postgres types. As an example: just because we know something is in an integer in ecto or elixir does not mean we can encode it to a postgres type, because they have int2, int4, int8, etc.

**Comment by josevalim** [comment]
> As an example: just because we know something is in an integer in ecto or elixir does not mean we can encode it to a postgres type, because they have int2, int4, int8, etc.

Ahh, true. :(

**Comment by OvermindDL1** [comment]
Hmm, what if it was a typing function that specifically used database level types rather than Ecto types, is that sufficient?  Most of the time I'd be using a type from a field already in the query anyway if at all possible.

**Comment by ericmj** [comment]
It might be possible if you create a custom ecto and postgres type like @josevalim said. We would also need have to add an exact mapping between the ecto and postgres type. Today we don't have this mapping because there is nothing that ties an ecto type to the underlying database.

**Comment by methyl** [comment]
@OvermindDL1 
As you were using raw SQL for this as well, how did you handle escaping since
> Ecto avoids doing manually escaping because it's fragile and hard to do for every supported type.

**Comment by OvermindDL1** [comment]
@methyl very hard-coded things with interpolated restricted string values that aren't user controlled in any way.  ^.^;

Not a generic way *at* *all*.  Hence why I would really like it being in Ecto.  :-)

**Comment by OvermindDL1** [comment]
As an example usage of the issue itself, I just wrote this horror...  ^.^;
```elixir
        {type, section_courses}, squery when type in [:subject_course, :subject_course_seq] ->
          section_courses =
            section_courses
            |> Enum.map(&"#{elem(&1, 0)}-#{elem(&1, 1)}-#{elem(&1, 2)}")

          where(
            squery,
            [course, section, dept],
            fragment(
              "? || '-' || ? || '-' || ?",
              section.ssbsect_subj_code,
              section.ssbsect_crse_numb,
              section.ssbsect_seq_numb
            ) in ^section_courses
          )
```
Which has both an extra (fairly significant) runtime cost and is significantly longer than what one would expect it to be (and I can't change the DB schema, it's part of the 20-year-old system), and this only works because I know `-` can't appear in the values so no chance of overlap and they happen to all be strings (practically everything in the 20-year old+ system is strings, yay stringly typing...  ^.^;).  And it's not easy to pull out into a standalone query because this is part of a *massive* ecto query generator.

**Comment by methyl** [comment]
That won't use indexes unfortunately which makes it not feasible for my usecase. I'll probably keep composing raw sql for the time being :)

**Comment by OvermindDL1** [comment]
> That won't use indexes unfortunately which makes it not feasible for my usecase. I'll probably keep composing raw sql for the time being :)

I didn't have that choice, this database feels older than I am and I have no control over it, already no indexes on anything but primary keys, which makes some of the larger multi-million-row queries... fun...  ^.^;

Having the ability for composite fields would be such a huge help though both for these purposes as well as foreign keys!  Maybe a meta-issue for it to grab attention for potential PR's?

**Comment by tpitale** [comment]
> in case someone wants to put in the work

@josevalim @ericmj What was the final decision about how this could work? I'm happy to try to put in the work. It made _some_ sense to me that maybe if the fields of the compound key are defined, we could get the type info from the database, and map positionally to a list of tuples:

```
from(x in Y, where: {x.field1, x.field2} in ^list_of_typles_for_those_two_fields)
```

**Comment by josevalim** [comment]
That would be the Ecto syntax, yes. :) But the tricky part is encoding a list of tuples in Postgrex. See this earlier comment: https://github.com/elixir-ecto/ecto/issues/1457#issuecomment-461085711
