### ISSUE TITLE
Add comment option to migration

### ISSUE THREAD

**Issue by yaBliznyk** [elixir-ecto/ecto#1531]
I think this must looks like this:

```
create table(:table_name, comment: "Table comment") do
      add :title, :string, size: 150, null: false, comment: "My comment to title"
end
```

I try execute this code and not seen comment in table.
http://joxi.ru/DmB7j3QuNon3q2
"Комментарий" is comment in Russian))

http://joxi.ru/82QWlGkf1G0X3r
Documentation don`t have option "comment"

**Comment by eniolopes** [comment]
I took the liberty to look into doing this for PostgreSQL.

The way comments are added to tables and columns on PostgreSQL is through a separate query, which means there is no special constraint to add the comment when creating the table. I've got something working for adding the comment to a table [here](https://github.com/eniolopes/ecto/commit/8d47685d71438df439b7d7ec6331e0f6e088ddaa).
Please advise if this approach is ok, I'm not sure if adding  `comment` to `%Table{}` is desired or not.

Following this same implementation for columns will be a little tricky, because options for columns are only extracted via `column_definitions/2`, which means I won't be able to concatenate the query to add comments at the end. What I can think of is having a function that builds comments queries for columns and call it in `excute_ddl/3`.

PS: I wasn't intending to implement this without asking permission first, sorry. I actually was just reading through the code to see if I could find it and it turned out not so hard of change.

**Comment by josevalim** [comment]
@eniolopes it is totally fine to go ahead and implement it. :D Putting it in `%Table` is the best option for now.

However, if the comment option is not really supported by columns and we would have to collect them, I would rather prefer to not support them. Something else to consider is how comments are going to work with alter table comments.

**Comment by eniolopes** [comment]
@josevalim cool, will go ahead then. I think we will be fine supporting it for columns as well. Will take a look at the behaviour for alter tables. Thanks :)
