### ISSUE TITLE
Verify Binary Strings are Printable 

### ISSUE THREAD

**Issue by jeregrine** [elixir-ecto/ecto#161]
https://github.com/elixir-lang/ecto/blob/master/lib/ecto/query/util.ex#L61

**Comment by josevalim** [comment]
I still think this should not be done in Ecto because of the reasons above. Both Jason and Plug will guarantee no bad UTF-8 will enter the system. In other words, if bad UTF-8 is reaching Ecto, it is likely already too late. Is this coming from Hex' custom parsers? If so, i would guarantee proper encoding when parsing.

**Comment by wojtekmach** [comment]
@josevalim it comes from metadata inside tarball. Agreed, we should ensure it when extracting the tarball 👍
