### ISSUE TITLE
Add on_replace: :update tests to embedded_test and embedded_no_pk_test

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1680]
/cc @eniolopes

**Comment by eniolopes** [comment]
:+1:

**Comment by josevalim** [comment]
@eniolopes just to confirm, will you send a PR or should we add those ones? :)

**Comment by eniolopes** [comment]
I can add it if you guys can wait until the weekend 

On Wed, Sep 14, 2016 at 02:05 "José Valim"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/eniolopes
just to confirm, will you send a PR or should we add those ones? :)

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/elixir-ecto/ecto/issues/1680#issuecomment-246951028
, or

**Comment by josevalim** [comment]
Yup, we can definitely wait!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
@eniolopes ping :)

**Comment by eniolopes** [comment]
@josevalim started working it today, do we want the replacement to happen for all embedded association or only for `embeds_one`?

**Comment by josevalim** [comment]
I believe only embeds_one because we can't update on embeds_many cases.
