### ISSUE TITLE
Possible bug related to Exq

### ISSUE THREAD

**Issue by taylordowns2000** [elixir-ecto/ecto#1773]
Hi there! For quick context: I work on an integration platform for international development (health, education, livelihoods, etc.) organizations with @stuartc and we use both Ecto and [Exq](https://github.com/akira/exq).  (I'm [cross-posting this](https://github.com/akira/exq/issues/220) on the Exq repo as well.)

Messages are sent to our platform and then routed to specific `jobs`—what we call miniature Javascript programs that transform the source data and send it along to some other system. Since installing Exq, I've noticed that Ecto throws a `NoResultsError` for about 10% of the queries which _should yield results_ when they are executed from within Exq. It's a frustratingly low rate of occurrence and I am unable to reproduce it except from within Exq. In other words, when I run the same query you see below from IEX, it _always_ succeeds.

```ex
%Exq.Support.Job{args: [%{"job_id" => 296, "receipt_id" => 180841,
      "trigger_id" => 265, "type" => "ReceiptMatch"}],
   class: "OpenFn.JobRunner", enqueued_at: 1477660802.624432,
   error_class: "ExqGenericError",
   error_message: "{%Ecto.NoResultsError{message: \"expected at least one result but got none in query:\\n\\nfrom j in OpenFn.Job,\\n  where: j.id == ^296\\n\"},\n [{Ecto.Repo.Queryable, :one!, 4,\n   [file: 'lib/ecto/repo/queryable.ex', line: 74]},\n  {OpenFn.ReceiptMatch, :from_map, 1,\n   [file: 'web/models/receipt_match.ex', line: 29]},\n  {OpenFn.JobRunner, :perform, 1,\n   [file: 'lib/open_fn/job_runner.ex', line: 23]},\n  {Exq.Worker.Server, :\"-dispatch_work/2-fun-0-\", 3,\n   [file: 'lib/exq/worker/server.ex', line: 119]}]}",
   failed_at: 1477660802.634262, finished_at: nil,
   jid: "3a9e9f12-de3e-4c76-9906-0eaa806a6a44", processor: nil, queue: "runs",
   retry: true, retry_count: 0}
```

I would expect something more along the lines of `repo OpenFn.Repo is not started, please ensure it is part of your supervision tree` or `Repo not available` but for these seemingly random 10% of queries sent from Exq, we get what looks like a completely functional Repo... but no results in the DB when we are certain that those records (e.g., a job with id `296` for the above snippet) really do exist.

Has anyone come across this issue before? Thanks so much for your help!

Taylor

**Comment by josevalim** [comment]
If you believe this is a bug in Ecto, please use the issue template and provide the proper information. If you don't think this is a bug and you would like guidance, then the mailing list is a better forum for discussion.

However, I don't believe it is something suspicious happening with Ecto but rather that the database entry indeed does not exist. In particular, make sure that you are not queueing jobs inside a transaction (or something that runs inside a transaction such as a changeset or multi), otherwise, the job may run before the transaction commits which would mean the job indeed is not yet visible in the database for other connections.

**Comment by taylordowns2000** [comment]
Thank you, José. I'm sorry to have missed the issue template and thank you for the mailing list suggestion. Will also explore your pointer re: jobs inside a transaction!

**Comment by taylordowns2000** [comment]
José, just for the record, this was truly a boneheaded move on my part but maybe worth noting for others...

I run a "staging" server and a "production" server. Of course, I want staging to run with precisely the same config as production, save a few specific environment variables. You can probably see where this is going...

I forgot to set `namespace: System.get_env("EXQ_NAMESPACE")` in the config. Instead, I had the namespace hard coded in my config and two instances of Exq were effectively stealing each other's jobs from Redis. It worked sometimes, but just didn't sometimes—seemingly _without a trace_!

Using an environment variable for `namespace` solved the issue. Thanks again for you support!

**Comment by rranelli** [comment]
The work stealing is also something that happens when you're doing deployments. 
The work scheduled by a previous version might be scheduled in a node in a newer version and vice-versa.

I've had my share of problems like this more than once. The simplest solution I'd recommend to avoid this issue is stop exq's application in all your nodes *before* rolling out the new code.
