### ISSUE TITLE
Use iodata when building SQL queries

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1799]
Let's do it by parts so we don't have one big PR. :)

I believe the adapter should still return a binary (because of query caching) but the building can be done with iodata and then we can call IO.iodata_to_binary once at the end.

**Comment by michalmuskala** [comment]
It's funny that you mention it, since I was working on it some time ago, but didn't finish. I have regular query generation for postgres (excluding ddl).

Through my measurements I didn't notice any significant speed difference, though I assume the GC pressure would be much lower since it would be producing less garbage. It might be that I messed up with the measurements.

**Comment by squaresurf** [comment]
Shoulds this still be open since #1802 is merged?

**Comment by josevalim** [comment]
This is pending removing the IO data conversion from adapters and doing it in the connection. This will benefit particularly insert_all.
