### ISSUE TITLE
Provide Repo.init callback for dynamic configuration

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/ecto#1828]

**Comment by josevalim** [comment]
I think we should make it `init/2` and also pass the environment as argument. WDYT @fishcakez @michalmuskala?

**Comment by michalmuskala** [comment]
I don't think it's a good idea. We should still use mix config for the configuration and managing the environment. It's just that we make it explicit how it gets there.

**Comment by josevalim** [comment]
@michalmuskala so how we are going to configure the URL dynamically only for production? Can you provide an actual code sample?

**Comment by michalmuskala** [comment]
One way would be doing something like this:

```elixir
def init(_) do
  conifg = Application.fetch_env!(:app, __MODULE__)
  if database_url = System.get_env("DATABASE_URL") do
    {:ok, Keyword.merge(config, Ecto.Repo.parse_url(database_url)}
  else
    {:ok, config}
  end
end
```
So whenever the `DATABASE_URL` is set, we use it instead of the config values.

The advantage is that it's explicit on what's happening and since it's happening at runtime it's very easy to change and modify.

Another, maybe better, way could be:

```elixir
def init(_) do
  conifg = Application.fetch_env!(:app, __MODULE__)
  if database_url = maybe_system(config[:url]) do
    {:ok, Keyword.merge(config, Ecto.Repo.parse_url(database_url)}
  else
    {:ok, config}
  end
end

defp maybe_system({:system, name}), do: System.get_env(name)
defp maybe_system(other), do: other
```

This has exactly the same behaviour as we have right now, but it's all happening in the user's code instead of inside ecto.

**Comment by josevalim** [comment]
I see, thanks. I think we should pass the config in anyway, no reason to ask the user to read it almost always. If they don't want it, they can simply not use it.

**Comment by michalmuskala** [comment]
So I would prefer to have something like this, instead:
```elixir
worker(MyRepo, [Application.fetch_env!(myapp, MyRepo])
```
in the supervisor and later you receive the config as argument in the init.

**Comment by josevalim** [comment]
@michalmuskala what would we be possibly gaining with it?

**Comment by michalmuskala** [comment]
It's explicit, if user wants to do something else, it's clear where to change it, and we no longer need the `otp_app` hack.

**Comment by josevalim** [comment]
@michalmuskala I am not sure I buy it. The user no longer needs to pass otp_app on `use` but the same otp_app is now hardcoded in the same module. Just a couple lines below.

Explicit is general a good reason but we need to have something to gain for it. Otherwise why have abstractions? Furthremore, I don't expect everyone will have to define a `init` function and it would be unnecessary to force people to do it if they don't need dynamic configuration.

**Comment by josevalim** [comment]
Plus there is theoretically no need to use `init` if we could simply support those options to be given on start:

    supervisor(Repo, [url: System.get_env("DATABASE_URL")])

**Comment by michalmuskala** [comment]
Most of the time the `Repo` module is generated, so it doesn't really matter if we have a bit more code there.

The huge advantage of `init` is that it's a regular function invoked at runtime, where config evaluation happens effectively in different stages depending on how you deploy or package your application. Also, defining the `init/1` in repo makes it very similar to how supervisor works - you define `init/1` that returns the configuration.

---

Coming back to the compile-time configuration. What options are we using at compile-time? I think it would make sense to pass compile-time options directly to `use Ecto.Repo` and leave runtime options to be either returned by the `init/1` callback or passed in from the supervisor.

I like the suggestion to pass url from supervisor, the problem is that we want to do this conditionally - only in production, so we don't want to always read it.

**Comment by josevalim** [comment]
> Most of the time the Repo module is generated, so it doesn't really matter if we have a bit more code there.

That should not be used as an excuse to generate code that does not need to be generated.

>  I think it would make sense to pass compile-time options directly to use Ecto.Repo and leave runtime options to be either returned by the init/1 callback or passed in from the supervisor.

That pushes the complexity all up to the user of the API. Now they need to know where we need to configure key `:a` and key `:b` and the answer is going to be tied to an implementation detail, which may even change between releases.

> I like the suggestion to pass url from supervisor, the problem is that we want to do this conditionally - only in production, so we don't want to always read it.

Why? Why are we worried about always reading it?

**Comment by josevalim** [comment]
After attempting to write a patch for this I realized there is a bigger problem: configuration specfied on `def init` won't be available on `ecto.create` or `ecto.drop` because we cannot start the repository for running those operations (specially `ecto.create` since the database does not yet exist). Or we need to have a `type` flag being passed to `init/2` or we need to find another solution.
