### ISSUE TITLE
Ecto.Changeset.no_assoc_constraint/3 doesn't generate errors with PostgreSQL

### ISSUE THREAD

**Issue by ThijsWouters** [elixir-ecto/ecto#1844]
### Environment

* Elixir version (elixir -v): 1.3.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.1.19
* Ecto version (mix deps): 2.0.6
* Database adapter and version (mix deps): postgrex 0.12.1
* Operating system: Ubuntu Linux

### Setup
```
defmodule User do
  use Ecto.Schema
  
  schema "users" do
    has_many :transactions, Transaction
  end
end

defmodule Transaction do
  use Ecto.Schema

  schema "transactions" do
    belongs_to :user, User
  end
end

# create user
user = Repo.insert! %User{}

# create transaction for that user
Repo.insert! %Transaction{user: user}

# delete user
user
|> Ecto.change
|> Ecto.no_assoc_constraint(:transactions)
|> Repo.delete
```

### Current behavior

Raises a `Ecto.ConstraintError`

### Expected behavior

Sets an error in the changeset.

**Comment by josevalim** [comment]
Thank you for the report. Can you please show me your migration code as well?

**Comment by josevalim** [comment]
Actually, nevermind, I totally know where the issue is. :) It is related to your PG version.

Can you please try running Ecto's PG test suite? Something like this: `MIX_ENV=pg mix test`. You may see failures related to constraints, if so, they are due to the parsing code here: https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/adapters/postgres/connection.ex#L30-L54

**Comment by josevalim** [comment]
@ThijsWouters I started a branch that runs 9.2 tests on CI and I was able to reproduce the failures: https://github.com/elixir-ecto/ecto/pull/1845

I am working on a fix. :)

**Comment by ThijsWouters** [comment]
Great, thanks!

**Comment by ThijsWouters** [comment]
I tried it and it works now. Thank you!!
