### ISSUE TITLE
have any function like  real_msyql_real_escape_string  in php?!

### ISSUE THREAD

**Issue by xcwen** [elixir-ecto/ecto#1878]
have any function like  real_msyql_real_escape_string  in php?!
```php
$mysqli = new mysqli("localhost", "root", "xxx");
echo  $mysqli->msyql_real_escape_string ( "'asdfa'\"fadf "); #=> \'asdfa\'\"fadf 
```

**Comment by michalmuskala** [comment]
Please use the elixir forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you.

---

Since ecto strongly discourages interpolating into the SQL itself, and instead promotes usage of prepared statements and arguments, escaping is not needed most of the time.

**Comment by xcwen** [comment]
thanks :>
