### ISSUE TITLE
Allow `put_assoc` with query instead of list of models

### ISSUE THREAD

**Issue by hauleth** [elixir-ecto/ecto#1881]
It would be great if `Ecto.Changeset.put_assoc` would allow using query as an third parameter. Proposed syntax:

```elixir
changeset
|> put_assoc(:assoc, from item in model, where: item.id in ^ids)
```

**Comment by josevalim** [comment]
Can you please provide more information? For example, when would the query be executed? What are the benefits of such approach? Etc.

**Comment by hauleth** [comment]
My use case is that I have user-like model that has many `has_one` relations where some of them has their own relations and I want to update whole tree at once. Example:

```elixir
defmodule A do
  use Ecto.Schema
  import Ecto.Changeset

  schema "a" do
    has_one :bs, B
  end

  def changeset(struct, a_params \\ %{}) do
    struct
    |> cast(...)
    |> cast_assoc(:b, a_params["b"])
  end
end

defmodule B do
  use Ecto.Schema

  schema "b" do
    belongs_to :a, A

    many_to_many :cs, C, join_table: "bs_cs"
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(...)
    # what should I put there that I could update `cs` without additional query and some complex changes into `params`
  end
end

defmodule C do
  use Ecto.Schema

  schema "c" do
  end
end
```

Where `C`s are managed independently from `B` (i.e. tags). And I want to update `A` and `B` by connecting `C`s by `id`. Example JSON request:

```json
{
  "a": {
    "b": { "cs": [1,2,3] }
  }
}
```

So I would like to not fetch all `C`s if possible, as:

1. I would not like to make such nested change in `a_params` if it would e possible.
2. As I am using Postgres UUID feature it is highly unlikely to have ID collision between tables, so I would like connect 2 tables based only on ID and leave checks to the Postgres constraints.

**Comment by josevalim** [comment]
If you want to directly update "cs", then you can issue a `delete_all`+`insert_all` to directly remove and introduce entries to the join table. I believe though `insert_all` will fail if any UUID does not exist so you may need to convert it into multiple inserts.

The other option is to use `delete_all`+`INSERT INTO SELECT`. The latter which is not support through an Ecto API at the moment but you can always write as a direct query.

I am still not convinced though any of those two solutions would be a good fit for put_assoc. Based on all other functionality in changesets, I would expect the query version to perform a query and build changesets behind the scenes, which is NOT what you want.

The solution would have in mind would use INSERT INTO SELECT but we would first need to support such API into `insert_all` and then study the possibility of being able to rewrite such on put_assoc (which again, I am not sure is a good fit for put_assoc).

So if we are going to get a feature out of this proposal, it would be to support INSERT INTO SELECT in Ecto. It would probably be a good addition to Ecto so if someone wants to send a PR or start a discussion, please go ahead, otherwise it is a low priority feature for the Ecto team to work on.

**Comment by SylvainBigonneau** [comment]
> So if we are going to get a feature out of this proposal, it would be to support INSERT INTO SELECT in Ecto. It would probably be a good addition to Ecto so if someone wants to send a PR or start a discussion, please go ahead, otherwise it is a low priority feature for the Ecto team to work on.

Has this issue been tackled as of today? I am actually looking for a feature like this one.

**Comment by josevalim** [comment]
No, we don't support it (yet).
