### ISSUE TITLE
Refactor migrator tasks to use common arg parser

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1886]
Both migration tasks use the same args, we should be able to have a single place where the args are parsed and sanitised.

https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.migrate.ex#L52-L67

https://github.com/elixir-ecto/ecto/blob/master/lib/mix/tasks/ecto.rollback.ex#L52-L67

This should be started only after https://github.com/elixir-ecto/ecto/pull/1885 is merged.

**Comment by josevalim** [comment]
To me that's a positive duplication. The code is almost on its own declarative and built on top of shared functions. Trying to abstract it away will likely lead to a more complex code, because it needs now to handle things like different defaults for the `all || step || to` check and so on. Maybe if there is something to be abstracted, it is the quiet handling, but that would be pretty much it.

**Comment by michalmuskala** [comment]
You're right. I admit, I missed the difference in the handling of the `all || step || to` case.
