### ISSUE TITLE
Scale without precision on decimal/numeric not working (mysql)

### ISSUE THREAD

**Issue by trtstm** [elixir-ecto/ecto#1946]
add :price, :decimal, scale: 4

Ecto will generate this query:

    price decimal

instead of

    price decimal(10,4)

The last one seems more logical because mysql will set the default value for decimal/numeric to 'decimal(10,0)'.

**Comment by josevalim** [comment]
Maybe it is better to raise if scale was given but not precision.

**Comment by shulhi** [comment]
Is it possible to raise during compile time?

**Comment by ericmj** [comment]
> Is it possible to raise during compile time?

Migrations are compiled when they are run so I don't think the distinction matters in this case.

**Comment by shulhi** [comment]
I think I can work on this, I had it check for the condition and throwing error. Is there a specific error that needs to be thrown? Currently it is just throwing `:error`, but I reckon a more descriptive error is better. Suggestion to  handle the error is welcomed since this is my first PR to tackle.
