### ISSUE TITLE
raise if preload query contains limit or offset

### ISSUE THREAD

**Issue by michalmuskala** [elixir-ecto/ecto#1956]
It will never produce the desired result and is just plain confusing. We should bail out early, probably explaining why it won't work.

**Comment by josevalim** [comment]
@michalmuskala I would rather not forbid it because maybe someone wants to bring the top 100 most voted comments across a list of posts. Passing a query to preload is already somewhat an advanced feature, so I would leave it as is but add extra notes to the docs where we describe the ability to give queries to preload.

**Comment by michalmuskala** [comment]
People trip on this all the time, I think I saw 4 or 5 questions about this, only last week. I'm not sure adding a line in the docs will help.

**Comment by josevalim** [comment]
@michalmuskala well, it is like doing a LIMIT or OFFSET when are doing an aggregation such as count. People trip on it all the time but I don't think we should forbid valid SQL constructs.

**Comment by laurocaetano** [comment]
> so I would leave it as is but add extra notes to the docs where we describe the ability to give queries to preload.

Isn't it already [there](https://github.com/elixir-ecto/ecto/blob/17bd59199372ebb3f47cd93eb872b84ee072e246/lib/ecto/query.ex#L1129-L1138)?

**Comment by josevalim** [comment]
@laurocaetano tks! :heart:
