### ISSUE TITLE
Support for preloading fragments

### ISSUE THREAD

**Issue by wfgilman** [elixir-ecto/ecto#2142]
I came across this limitation as I tried to load data from a lateral join. The details of my specific use case are laid out in [this forum thread](https://elixirforum.com/t/help-with-ecto-query-fetching-nested-associations/7192) and [this thread post](https://elixirforum.com/t/preloading-top-comments-for-posts-in-ecto/1052/12).

Fragments are unique because they are the only way to pass a parameter to a subquery. I use this querying technique often when returning time series data associated with an entity, e.g. an account with the latest balance. Being able to load the results of the fragment would be incredibly helpful. I assume this would require the ability to cast a fragment as a schema.

### Environment

* Elixir version (elixir -v): 1.4.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.5.4
* Ecto version (mix deps): 2.1.4
* Database adapter and version (mix deps): postgrex 0.13.2

Here's the example from the thread post linked above:

Schema
```
CREATE TABLE account (
  id serial PRIMARY KEY,
  name CHAR
);
CREATE TABLE balance (
  id serial PRIMARY KEY,
  date DATE,
  amount NUMERIC(12,2),
  account_id serial REFERENCES account (id)
);
```
SQL Query
```
SELECT a.name, b.amount 
FROM account AS a 
JOIN LATERAL (
  SELECT * 
  FROM balance AS b 
  WHERE b.account_id = a.id 
  ORDER BY date DESC 
  LIMIT 1
) b ON true;
```
Result
```
   name   | amount
----------+---------
 Checking | 2858.51
 Savings  | 1307.17
```
Ecto Equivalent
```
Account
|> join(:inner_lateral, [a], b in fragment("SELECT * FROM balance WHERE account_id = ? ORDER BY date DESC LIMIT 1", a.id))
|> preload([a, b], [balance: b])
|> Repo.all()
```
Raises:
```
** (Ecto.QueryError) associationStorage.Schema.Account.balancein preload requires an inner or left join, got inner_lateral join in query:
```

**Comment by josevalim** [comment]
Unfortunately we cannot support fragments because we don't know the shape of the data that is coming in. In order for it to work, you would need to select all fields in the fragment in the exact same order as they are listed in your schema and that is very confusing and error prone.

The first step would likely be to support subqueries with parameters. This would allow us to get preloads somewhat for free. We have no plans for tackling those though, so feel fee to contribute such features.
