### ISSUE TITLE
Not able to connect to Rails database with Ecto 2.2.1

### ISSUE THREAD

**Issue by arunthampi** [elixir-ecto/ecto#2192]
### Environment

* Elixir version (elixir -v): 1.4.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6.3
* Ecto version (mix deps): 2.2.1
* Database adapter and version (mix deps): postgrex 0.13.3
* Operating system: macOS 10.12.5

### Current behavior

When trying to connect to a Rails database in a Phoenix app with Ecto 2.2.1, we get this error:

```
** (ArgumentError) cannot load `"20130309050018"` as type :integer
    (ecto) lib/ecto/repo/queryable.ex:313: Ecto.Repo.Queryable.load!/5
    (ecto) lib/ecto/repo/queryable.ex:255: Ecto.Repo.Queryable.process/5
    (ecto) lib/ecto/repo/queryable.ex:189: anonymous fn/4 in Ecto.Repo.Queryable.postprocessor/4
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/ecto/repo/queryable.ex:139: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/migrator.ex:300: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:157: Ecto.Migrator.run/4
    (ecto) lib/ecto/adapters/sql/sandbox.ex:522: Ecto.Adapters.SQL.Sandbox.unboxed_run/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:81: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (elixir) lib/file.ex:1162: File.cd!/2
    (mix) lib/mix/project_stack.ex:86: Mix.ProjectStack.root/1
    (mix) lib/mix/task.ex:332: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:265: Mix.Task.run/2
    (mix) lib/mix/project.ex:313: Mix.Project.in_project/4
    (elixir) lib/file.ex:1162: File.cd!/2
    (mix) lib/mix/task.ex:400: anonymous fn/4 in Mix.Task.recur/1
```
The `version` column in the `schema_migrations` table in Rails is of type `varchar` but it looks like Ecto expects it to be an integer? This used to work fine with Ecto version 2.1.6

### Expected behavior

This error should not happen (did not happen with Ecto 2.1.6)

**Comment by josevalim** [comment]
@arunthampi it certainly never worked before since Ecto would raise and one of the things we did still on the 2.1 release was to improve the error messages.  Can you please double check? And you can also change the migrations table for Ecto by setting migration_source in your repo configuration or in Rails.

**Comment by warmwaffles** [comment]
@josevalim this certainly does put a bit of a wrench in to the projects that are trying to transition from a rails application to a phoenix app, but running both simultaneously while parts are migrated out. Is there a way to tell ecto which table to use for migrations in a config?

We can not change the name of that column without breaking our existing rails application, nor can we update ecto because it requires the integer column.

**Comment by warmwaffles** [comment]
I see this exists: 

https://github.com/elixir-ecto/ecto/blob/60015fa9fddfda347ae947ec6d8314bf19feebb0/lib/ecto/adapters/postgres.ex#L156

So I should be able to define `config :appname, MyRepo, migration_source: "new_migration_table"` right?

**Comment by michalmuskala** [comment]
Yes, you can configure the `migration_source` option to change the table name - this is exactly what José referred to. You can read more on it in the [`Ecto.Migration` module doc](https://hexdocs.pm/ecto/Ecto.Migration.html#module-repo-configuration)

**Comment by warmwaffles** [comment]
Thanks @michalmuskala this did the trick for us. Now we are hitting other issues not related to ecto, but ex_machina.
