### ISSUE TITLE
Preloader forces early evaluation/collection of Repo.stream (2.1+, inc master)

### ISSUE THREAD

**Issue by rhetzler** [elixir-ecto/ecto#2274]
Repo.all and Repo.stream both pass through Ecto.Repo.Preloader.query/5, which forces evaluation/collection of the enumerable. This was probably already an issue when Repo.stream was introduced in https://github.com/elixir-ecto/ecto/commit/4f7d1fdcf627995444362c7724a69d02d64bf5ea ( @fishcakez )
since Preloader.query was written (to be fair) long before Repo.stream and not with streaming in mind.

1. Ecto.Repo.{all,stream} delegate to Ecto.Repo.Queryable.{all,stream}/4
https://github.com/elixir-ecto/ecto/blob/v2.1/lib/ecto/repo.ex#L146-L152
2. Ecto.Repo.Queryable.{all,stream}/4 chain to Ecto.Repo.Queryable.{execute,stream}/5
https://github.com/elixir-ecto/ecto/blob/v2.1/lib/ecto/repo/queryable.ex#L29-L45
3. Ecto.Repo.Queryable.{execute,stream}/5  **both** invoke Ecto.Repo.Preloader.query/5
https://github.com/elixir-ecto/ecto/blob/v2.1/lib/ecto/repo/queryable.ex#L121-L160
4. Ecto.Repo.Preloader.query/5 forces early evaluation
https://github.com/elixir-ecto/ecto/blob/v2.1/lib/ecto/repo/preloader.ex#L12-L25

The primary concern is that if no preloads are required ("the empty case"), there should be no reason to collect the enumerable.
https://github.com/elixir-ecto/ecto/blob/v2.1/lib/ecto/repo/preloader.ex#L14
I believe that this would cover the vast majority of streaming scenarios.

If preloads are required, perhaps the collection is unavoidable ( preload gurus will know better than me ), but this implementation should not force early collection in the empty case.

**Comment by rhetzler** [comment]
ok, it seems the intent was to have the preloader work on batches, wherein any given batch could be expected to have already been collected/evaluated.

The underlying driver has the option of providing:
1. a single batch backed by a stream:
 ```[{nil, stream}]``` 
2. a stream of batches size 1:
 ```Stream.map(stream, &{nil, [&1]})```
3. anything in between, depending on implementation.

The first option will fail if the batch is itself a stream, the second option will succeed but may result in n-queries preloads, and a third option may succeed with better performance if it manually handles the batching. perhaps this is what @fishcakez  was aiming for.

Closing this and fixing the driver to use 2 instead of 1

**Comment by fishcakez** [comment]
The API is designed for a stream that chunks into batches of size N (SQL drivers default to 500 rows). It will handle preload for each chunk as it is fetched. In SQL we are always inside a transaction and want to read the preloads at the same time we do the main query (fetch) to ensure data consistency as best we can. Therefore if there are 2000 rows and 3 preloads, we fetch 4 chunks of 500 and execute 12 (4 * 3) preload queries.

This design should fit well if using a cursor implementation directly at the wire protocol level with most databases. If there is a driver that abstracts this in between the Ecto layer it may work very poorly. The design was to fit with what already existed for SQL drivers so might not fit with your needs and we can look into changing the API in 3.0. It's likely we will change it then because the SQL drivers that support it (postgresql and mysql) will expose lower level cursor functions shortly.

**Comment by rhetzler** [comment]
Thanks for your feedback!

I'm looking at adding stream support into the mongodb_ecto/ecto-2.1 branch (mongodb driver has a streaming cursor already)

In the absence of preloads, exposing the underlying cursor directly to the stream seems ideal (ie, option 2 above), but with preloads, what you suggested (as i meant to infer with option 3 above) will yield better performance, i agree.

Thanks again & thanks for adding streaming to ecto in the first place!

**Comment by josevalim** [comment]
@rhetzler also note you don't need to add a comment to previous issues in reference to the new one. This makes maintainers receive 3 emails instead of only one. Thanks.
