### ISSUE TITLE
Using order_by results in half the results?

### ISSUE THREAD

**Issue by Harrisonl** [elixir-ecto/ecto#2297]
### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): 9.6.5
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): 0.13.3
* Operating system: MAC OSX

### Current behavior

When using the below query I will get half the number of results of the limit field when `order_by` is present:

e.g. if `limit: 8` i get 4 results. If `limit: 16` i get 8 results (for the queries I tested there was more then 50 results)

```elixir
    query = from a in ModA,
      limit: 8,
      order_by: [desc: a.int_value],
      offset: ^((page_number - 1) * 8),
 

    Repo.all(query)
```

where `a.int_value` is a non-null integer

Removing the `order_by` gives me the full amount set by the `limit` key.

### Expected behavior

Expect to receive the number of results designated by the `limit` query

Not sure if I am missing something here but from my (not-so-flash) sql knowledge, there shouldnt be anything wrong with it?

**Comment by michalmuskala** [comment]
This is caused by the preload though a join. When you join on a table, the database will return `n * m` results, the `limit` applies to that result.

When you preload from join for a `has_many` relation, ecto will deduplicate what database returns and fold into nice structs.

While I understand this behaviour might be surprising, it is expected and there's not much we can do. I would suggest removing preloading from the join and instead use regular preload that will issue two queries (but avoids this issue altogether and might be actually more efficient since it will only more `n + m` data over the wire instead of `n * m`).

**Comment by Harrisonl** [comment]
realised the problem - I had a preloads in the query as well (above query is truncated) which caused the results to be limited. Will dig into why

**Comment by Harrisonl** [comment]
@michalmuskala beat me to it! Thanks for the explanation, that makes sense.
