### ISSUE TITLE
build_assoc does not carry over the prefix

### ISSUE THREAD

**Issue by dustinfarris** [elixir-ecto/ecto#2308]
### Environment

* Elixir version (elixir -v): 1.5.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 10.1
* Ecto version (mix deps): 2.2.6
* Database adapter and version (mix deps): postgres 0.13.3
* Operating system: OSX and Debian

### Current behavior

`build_assoc` does not preserve prefix information

```
iex> post = Repo.get(Post, post_id, prefix: "something")
%Post{...}
iex> build_assoc(post, :comments, body: "Some comment") |> Repo.insert()
** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "comments" does not exist
```

The error is because Ecto forgot the prefix.  It must be supplied again explicitly to Repo.insert for this to work.

### Expected behavior

The prefix "something" should carry over into the resulting Comment struct from `build_assoc`.

**Comment by josevalim** [comment]
I am not sure if I fully agree. If you are using prefixes/schemas for organization purposes, then User could be in prefix "accounts" and Posts would be in another prefix, and you don't want that to propagate. That's why we usually only pass prefixes along if they come from a database operation. The best is for you to call put_meta and set the prefix or pass it on insert. Thanks!

**Comment by dustinfarris** [comment]
Good point.  I wasn't aware people use schemas in this way.  Thanks for the quick feedback!
