### ISSUE TITLE
Handling put_assoc with on_conflict: nothing

### ISSUE THREAD

**Issue by maxim** [elixir-ecto/ecto#2442]
**Note**: this issue is not like #1912 even though it deals with the same functions.

### Environment

* Elixir version (elixir -v): 1.6.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.6
* Ecto version (mix deps): 2.2.7
* Database adapter and version (mix deps): mariaex 0.8.3
* Operating system: MacOS Sierra / Ubuntu 16.04

### Current behavior

When you do

```elixir
changeset
|> put_assoc(SomeOtherRecord.changeset())
|> Repo.insert(on_conflict: :nothing)
```

and you do have a conflict, you will get an `Ecto.ConstraintError` on the foreign key constraint. That's because Ecto will attempt to insert the associated record despite having not inserted the parent.

### Expected behavior

In an ideal world this code would act the same way as when there is no `put_assoc`, simply return the in-memory schema. However, I'm not sure if it's possible. Would love to hear thoughts.

**Comment by josevalim** [comment]
Thanks for the report!

Unfortunately there isn't much we can do because the database does not give us much information about what happened. We know the ID is null, if it is was supposed to be generated in the database, but this is not a consistent behaviour and we don't know the reason why either.

I will make sure to document this behaviour, thank you!

**Comment by josevalim** [comment]
You can use Ecto.Multi in this case.
