### ISSUE TITLE
build_assoc

### ISSUE THREAD

**Issue by MeterSoft** [elixir-ecto/ecto#2453]
i have some trouble with create association
When i create association like 
`Ecto.build_assoc(domain, :locations, %{"country" => "USA"})`
country is blank but when i do
`Ecto.build_assoc(domain, :locations, %{"country": "USA"})`
it is ok. In origin code in controller it looks like this
`Ecto.build_assoc(domain, :locations, domain_location_params)`

**Comment by zoldar** [comment]
@MeterSoft If you want to build assoc using external input, [`Ecto.Changeset.put_assoc`](https://hexdocs.pm/ecto/Ecto.Changeset.html#put_assoc/4) and [`Ecto.Changeset.cast_assoc`](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3) are better suited for that task. `Ecto.build_assoc` expects attributes map as the third argument - it happens so that `%{"country": "USA"}` equals %{:"country" => "USA"}, where `:"country"` is the same as `:country`, hence your second attempt passed.

**Comment by ericmj** [comment]
@zoldar explained it very well. In the future please use Elixir Forum or Stack Overflow for questions.

**Comment by MeterSoft** [comment]
@zoldar my question is why this syntax is not work
`%{"country" => "USA"}`

Also can you please provide example how put_assoc will work in my case.

**Comment by josevalim** [comment]
@MeterSoft, as explained, please use Elixir Forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
