### ISSUE TITLE
Select TOP 1 on Repo.one()

### ISSUE THREAD

**Issue by acidhorse** [elixir-ecto/ecto#2505]
### Precheck

I would like to stop full table scans on mssql and I would suggest that Repo.one() should do by default.

### Environment

* Elixir version 1.6.1
* Mssql 2008 - 2012  and Azure
* Ecto version: ~> 2.2.8
* Database adapter and version (mix deps): mmsql_ecto: ~> 1.1.0)
* Operating system: Windows 10 / Azure deployments

### Current behavior  

Repo.one(query) does a select 'SELECT O0."id"'

### Expected behavior

Repo.one(query) does a 'SELECT TOP 1 O0."id"'

### Disclaimer
Apology: But I am not sure where to put this concern, feel free to put me correct (my first post).

**Comment by josevalim** [comment]
By definition `one` does not add a limit to queries because some queries are meant to return a single result by definition (for example, filtering on a unique index column). In case you get more than one result, it should fail (i.e. you forgot the index), and if we always add the limit we will never know about those. You can add TOP 1 / LIMIT 1 by using the query API.

**Comment by mauricew** [comment]
Actually was thinking of this and saw a middle ground that should be seriously considered: Entity Framework's equivalent being the LINQ `Single` implicitly does a `SELECT TOP 2` to check if there is more than one row returned.

**Comment by acidhorse** [comment]
I agree with Jose on this, I was being lazy, but he was too polite to mention that.

**Comment by mauricew** [comment]
I would not mind doing the implementation myself either, but there could be an argument to doing this since it's a potential background optimization that a user doesn't need to think about. Of course it's at the cost of adding a small quirk to the functionality of `Repo.one` directly changing a query, which thinking of the philosophy of this framework may not be the most desired thing to do.

**Comment by AndrewDryga** [comment]
@mauricew it will optimize only in cases where we raise exceptions (more than one), there is no reason to optimize it.

**Comment by zachdaniel** [comment]
@AndrewDryga I don't necessarily think that just because we raise an exception there means that optimization is pointless. If someone passes in the wrong query to `Repo.one` and it has a huge result set, then we could save them fro lots of network traffic, and time waiting for a bad query to run.

**Comment by zachdaniel** [comment]
I don't feel super strongly about it, just saying that if someone is willing to add it, and it just makes something faster w/o sacrificing anything, then I don't see why not.
