### ISSUE TITLE
Schema allows to define embed as field which causes weird error when using Repo.update

### ISSUE THREAD

**Issue by Eiji7** [elixir-ecto/ecto#2536]
### Environment

```elixir
$ asdf current
elixir         1.6.4-otp-20 (set by …)
erlang         20.3.2 (set by …)
postgres       10.3 (set by …)
```
Funtoo Linux current x86-64bit on intel64-ivybridge

I have tested it only on latest release and `master` branch. For second one my dependencies are:

```elixir
* postgrex 0.14.0-dev (https://github.com/elixir-ecto/postgrex.git) (mix)
  locked at 43aa6b9
  ok
* ecto 3.0.0-dev (https://github.com/elixir-ecto/ecto.git) (mix)
  locked at ce362f8
  ok
```

### Current behavior

`Repo.update` raises with `ArgumentError`
```
[error] #PID<0.447.0> running MyAppWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/graphiql
** (exit) an exception was raised:
    ** (ArgumentError) cannot dump embed `field_name`, invalid value: #Ecto.Changeset<action: :insert, changes: %{…}, errors: [], data: #MyApp.ModelName<>, valid?: true>
        (ecto) lib/ecto/type.ex:409: Ecto.Type.dump_embed/5
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/type.ex:387: Ecto.Type.dump_embed/3
        (ecto) lib/ecto/type.ex:398: anonymous fn/5 in Ecto.Type.dump_embed/5
        (stdlib) lists.erl:1263: :lists.foldl/3
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (ecto) lib/ecto/type.ex:387: Ecto.Type.dump_embed/3
        (ecto) lib/ecto/type.ex:730: Ecto.Type.process_dumpers/3
        (ecto) lib/ecto/repo/schema.ex:786: Ecto.Repo.Schema.dump_field!/6
        (ecto) lib/ecto/repo/schema.ex:799: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
        (stdlib) lists.erl:1263: :lists.foldl/3
        (ecto) lib/ecto/repo/schema.ex:797: Ecto.Repo.Schema.dump_fields!/5
        (ecto) lib/ecto/repo/schema.ex:746: Ecto.Repo.Schema.dump_changes!/6
        (ecto) lib/ecto/repo/schema.ex:274: anonymous fn/14 in Ecto.Repo.Schema.do_update/4
        (ecto) lib/ecto/repo/schema.ex:775: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
        (ecto) lib/ecto/adapters/sql.ex:577: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1933: DBConnection.run_transaction/4
        # my app stacktrace part which calls Repo.update
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
```

Where `field_name` is embedded (many) by another embedded field which is embedded (also many) by updated model.

The changeset is valid and there are no extra database checks.

### Expected behavior

It looks like a bug, because it's raising not only with `update!`, but also with `update` function, so it's expected to work rather than raise.

### Update

@wojtekmach found that problem comes both from `ecto` (but in schema rather than type - as in stacktrace) and my library.

My library copies fields in some models, because they are really similar. I forgot to add check for embedded fields and therefore my bad here is that I have declared `embed` as normal `field`.

The problem in `ecto` schema part is that such definition should raise.

**Comment by michalmuskala** [comment]
I think we'll need some sample code to reproduce. It seems to me a bit strange to have a changeset in that place - it seems as if the changeset was nested in a schema struct.

The `update!` vs `update` is about raising about the domain of the function, which is updating the data itself. Both of them are going to raise given bad arguments or when a connection to the database is not available.

**Comment by Eiji7** [comment]
@michalmuskala In short after call `MyApp.Model.changeset` I have `changeset` with `changes` with key which holds list of changesets - every changeset similarly has `changes` and in some key has list of changesets, so it's a bit complicated.

I will create an example app which reproduces problem soon.

**Comment by Eiji7** [comment]
ok, I have created simple `ecto` project:
```
git clone git@gitlab.com:ex-open-source/reproduce2536.git
cd reproduce2536
mix deps.get
mix test
```
This project also shows that this bug affects also old code (comparing to `master`) i.e.:
```
* postgrex 0.13.5 (Hex package) (mix)
  locked at 0.13.5 (postgrex) 3d931aba
  ok
* ecto 2.2.10 (Hex package) (mix)
  locked at 2.2.10 (ecto) e7366dc8
  ok
```
ping @michalmuskala

**Comment by michalmuskala** [comment]
Thanks, I'll take a look.

**Comment by Eiji7** [comment]
@michalmuskala: Hey, it's a week after this bug was reported and it's important for our app to have it solved asap. Of course I know that you have also other things to do, so I don't blame you. I would only ask if you have any progress (for example not pushed to git tree) and if I can try fix this issue in case you did not yet started to work on it yet.

**Comment by josevalim** [comment]
Hi @Eiji7! If the feature is important for your app, then the best is for your team to look into it and provide a bug fix. I imagine there are other bug fixes and features in the issues tracker that is important for other teams too and if we were to prioritize them as such, we would probably do it in a FIFO way, which means we wouldn't be able to get to this anytime soon. Thanks!

**Comment by wojtekmach** [comment]
@Eiji7 I found the issue:

1. trader embeds_many contacts ([link](https://gitlab.com/ex-open-source/invoicex/blob/b484a20eb36a7829b0be7c4f351c5cb9f57b427d/lib/invoicex/ecommerce/trader.ex#L18))
2. contact copies fields from other schema ([link](https://gitlab.com/ex-open-source/invoicex/blob/master/lib/invoicex/ecommerce/contact.ex#L19))
3. the code that copies fields ([link](https://gitlab.com/ex-open-source/invoicex/blob/b484a20eb36a7829b0be7c4f351c5cb9f57b427d/lib/invoicex/helper.ex#L7:L9)), is incorrect because it always uses `field/3` macro regardless if the thing is a field or an embed, for embeds it should have used `embeds_many` instead.

I think things could be improved on ecto side to crash earlier, when defining schema. We have a check here [link](https://github.com/elixir-ecto/ecto/blob/v2.2.10/lib/ecto/schema.ex#L1508), [link](https://github.com/elixir-ecto/ecto/blob/v2.2.10/lib/ecto/schema.ex#L1881) but currently it passes because: `Ecto.Type.primitive?({:embed, ...})`

> it's a week after this bug was reported and it's important for our app to have it solved asap

I think what would significantly speed up fixing the issue would be a more minimal repro. The example app was a bit helpful but I ended up digging into guts of your library which took time, which I don't mind, because it was **unfamiliar** codebase and things like macros (bingo), dependencies, dependency versions could be at play. I started by reproducing the issue in isolation and couldn't which made me think it's not an ecto issue. I ended up with this one-off script that reproduces the crash: https://gist.github.com/wojtekmach/0ff211c460e2d8ec2de0d46d38bfb8ce.

**Comment by Eiji7** [comment]
@wojtekmach: Wow, thank you so much! I did not even expected that issue is on my side. You saved me a lot of time. I will update this issue then to make sure other will not have similar problems in future.
