### ISSUE TITLE
Mixed migration rollback order

### ISSUE THREAD

**Issue by phunehehe** [elixir-ecto/ecto#2614]
### Environment

* Elixir version (elixir -v): 1.6.6
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 9.6
* Ecto version (mix deps): 2.2.10
* Database adapter and version (mix deps): postgrex 0.13.5
* Operating system: Alpine

### Current behaviour

1. Let's say I create a migration `20180701_first.exs`, but shelve the branch to work on something else.
2. Then I create another migration `20180702_second.exs`, finish and deploy it. Everything is good.
3. Then I go back to `20180701_first.exs`, finish and also deploy it. Everything is still good.
4. Now I find a problem with `20180701_first.exs` and want to roll back.

- `mix ecto.rollback` reverts `20180702_second.exs`.
- `mix ecto.rollback --to 20180701` reverts `20180702_second.exs`, then it also reverts `20180701_first.exs`.

### Expected behaviour

It's hard to say what should be expected here. Basically the problem happens because Ecto assumes the file name order is the same as the applied order.

One way is to honour the applied order:
- `mix ecto.rollback` should revert the latest migration that was applied, that is `20180701_first.exs`
- `mix ecto.rollback --to XXX` should revert migrations based on the applied order, i.e. first revert `20180701_first.exs`, then revert `20180702_second.exs`.

Another way is to honour the timestamp:
- At step (3), `ecto.migrate` should complain that the file name indicates an incompatible version. Then I can change the file name and things will be good again.

Thoughts?

**Comment by josevalim** [comment]
It seems that using the insertion time and define the order based on that is a good way to go.

**Comment by fertapric** [comment]
I have some doubts about using the insertion time to define the order. I think it might be confusing to order the list of `mix ecto.migrations` in a different order than the one defined in the migrations directory; or if the migrations are ordered using the timestamp (I guess this is less likely), then `--step`, `--to` and similar flags would be quite hard to use.

In addition, it could make migrations order inconsistent and different per environments. For example, if the both migrations given in the example  are rolled back and applied again, the order of the migrations would probably change because, in this new execution, migrations would be applied based on the timestamp.

Besides, for what I’ve experienced, the step (3) usually requires fixing conflicts in `db/structure.sql`. In such cases, I tend to generate a new timestamp and dump the database structure again. I’m aware this is my personal flow, but I wanted to mention it as a “workaround” for this issue :)

**Comment by phunehehe** [comment]
I ended up rejecting code that adds new migrations with old timestamps using this lousy script in CI:

```bash
if [[ -n ${CI_JOB_TOKEN:-} ]]
then
    url=https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/some-user/some-project
else
    url=git@gitlab.com:some-user/some-project.git
fi
git fetch $url

{
    git ls-files FETCH_HEAD path/to/migrations | tail --lines 1
    git log --name-only --diff-filter=A --format='' FETCH_HEAD.. path/to/migrations
} | sort --check
```

**Comment by phunehehe** [comment]
@josevalim would it be useful to (optionally) abort the migration in addition to emitting a warning? I can take a jab at adding a `--strict` flag if that helps.

**Comment by josevalim** [comment]
I think a better flag though would be --raise-on-unordered-versions or something similar. :)
