### ISSUE TITLE
Warn users trying to compare to charlists in Ecto Queries

### ISSUE THREAD

**Issue by Ch4s3** [elixir-ecto/ecto#2674]
Per: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-ecto/xLLEUvmxkyA/GoHTidY3FAAJ cc @josevalim 
### Environment

* Elixir version (elixir -v): any
* Database and version: Any, but specifically an issue for MySQL which doesn't have array types
* Ecto version (mix deps): 2.2
* Operating system: Any

### Current behavior
```elixir
  iex(1)> query = from(u in User where: (u.id == ^user.id and r.role_type == 'some role')
  iex(2)> Repo.all(query)
  ** (Ecto.QueryError) Array type is not supported by MySQL in query:
```

### Expected behavior
It would be good to give a compile time warning that `'some role'` is a char_list and not a string, and may cause unexpected runtime errors/behavior.

**Comment by umamaistempo** [comment]
Note that the compile-time check would have to analyze if the _code_ is a literal char_list instead of checking in the AST if it is a list of integers (I am not sure this is possible), otherwise, the problem I can see here is if a certain schema has a column that is `array(int)` and someone did the code:

```
Thing
|> where([t], t.affected == [1, 2, 3])
|> Repo.all()
```

Combine this with `warnings_as_errors` and we have applications that are unable to compile now.
