### ISSUE TITLE
Allow binding the last models without specifying the full binding list

### ISSUE THREAD

**Issue by ericmj** [elixir-ecto/ecto#275]
Use `...` to indicate you are binding the last models, the binding list should look like `[..., binding]`. Example:

``` elixir
where(query, [..., last], last.field == true)
```

/cc @rbishop

**Comment by jhosteny** [comment]
So I have a use case that seems like it could benefit from this. Suppose I have this query that I want to be composed eventually with others:

```elixir
def msas_visible_to(query, account) do
  from(msa in query,
    join: c in assoc(msa, :company),
    join: m in assoc(c,   :memberships),
    join: a in assoc(m,   :account),
    where: a.id == ^account.id and m.role == "admin")
end
```
I then have a price book, which belongs to an MSA (master service agreement). The price book can then have line items (products with prices per the MSA). I want to compose the above query with the following two:

In my PriceBook model:

```elixir
def for_msa(query) do
  from(m in query,
    join: pb in assoc(m, :price_book))
```

And the PriceBookLineItem model:

```elixir
def for_pricebook(query) do
  from(pb in query,
    join: pbli in assoc(m, :price_book_line_items))
```

And finally, the actual query I have to do:

```elixir
  MSA
  |> MSA.Queries.msas_visible_to(current_user)
  |> PriceBook.Queries.for_msa
  |> PriceBookLineItem.Queries.for_price_book
  |> Ecto.Query.select([msa, company, membership, account, pricebook], {pricebook})
```

The last select obviously makes the composition pretty brittle. Am I missing another way to do this? Otherwise this seems like it'd be pretty valuable.

**Comment by josevalim** [comment]
Hrm, can't you bulid the query from the opposite side? Starting at the line item?

**Comment by jhosteny** [comment]
@josevalim Thanks for the quick response. Let me think about that a bit. What I'm trying to accomplish is re-use of the `MSA.Queries.msas_visible_to` function (as well as others) An MSA joins two companies (a customer and vendor), and for example, I might have to reach into the vendor side:

```elixir
MSA
|> MSA.Queries.msas_visible_to(current_user)
|> MSA.Queries.vendor_admins_for
```

**Comment by josevalim** [comment]
It makes sense. We could also support this feature. It shouldn't be hard and we can use `...` for that:

    Ecto.Query.select([..., line_item], line_item)
    Ecto.Query.select([msg, ..., line_item], {msg, line_item})

**Comment by jhosteny** [comment]
Just to clarify my last comment - I think I could certainly reverse the construction of the query, but then I would need different queries on the MSA as the query source might be different, e.g. a vendor account or line item.

**Comment by jhosteny** [comment]
The utility of this would be diminished by the fact that you can't do a select and preload an association into the selected, joined table. So, I wouldn't worry about this for now. I'm just making a few more explicit queries.
