### ISSUE TITLE
String table names not working

### ISSUE THREAD

**Issue by michaelst** [elixir-ecto/ecto#2802]
### Environment

* Elixir version (elixir -v): 1.7.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 5.7.23
* Ecto version (mix deps): 3.0.1
* Database adapter and version (mix deps): mariaex 0.9.0
* Operating system: Mac OS X 10.14.1

### Current behavior

We have a lot of queries that we use just a string table name as we do not have schemas defined. This appears to be documented here as the first example: https://hexdocs.pm/ecto/Ecto.Query.html#content

```
# Imports only from/2 of Ecto.Query
import Ecto.Query, only: [from: 2]

# Create a query
query = from u in "users",
          where: u.age > 18,
          select: u.name

# Send the query to the repository
Repo.all(query)
```

This is one of the queries we receive the error on:
```
from(
  c in "caches",
  select: %{
    table: c.table,
    column: c.column,
    record_id: c.record_id
  },
  where: c.failure_count < 5,
  limit: 1_000
)
|> ZB.Repo.all()
```

However, we get this error

> ** (Ecto.QueryError) expected a from expression with a schema in query:

### Expected behavior
The queries to continue to work as they did with V2

**Comment by josevalim** [comment]
This should definitely work. Can you please include the full error message
as well as stacktrace?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michaelst** [comment]
```
     ** (Ecto.QueryError) expected a from expression with a schema in query:

     from z in "caches",
       where: z.id in ^["3907"],
       limit: 1

     code: ZB.Scheduled.DirtyCaches.run()

     stacktrace:
       (ecto) lib/ecto/query.ex:1844: Ecto.Query.assert_schema!/1
       (ecto) lib/ecto/query.ex:1836: Ecto.Query.order_by_pk/2
       (ecto) lib/ecto/query.ex:1782: Ecto.Query.first/2
       (zipbooks) lib/repo.ex:166: ZB.Repo.delete_all/2
       (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:765: Enum.each/2
       test/lib/zipbooks/chart_accounts/column_caches_test.exs:430: (test)
```

**Comment by josevalim** [comment]
That’s because there is no select expression. So we are attempting to
select everything which is only possible with schemas. The error message
was better in v2.0 though, we will see if we can improve it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michaelst** [comment]
Thanks, just found that in our code and realized it was that problem

**Comment by josevalim** [comment]
Wait, there is something more going on. Why is delete_all calling first? Do
you have a custom Repo extension or are you overring delete_all in repo by
any chance?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michaelst** [comment]
Ya we do this
```
  def delete_all(%{from: {_table, nil}} = queryable, opts), do: super(queryable, opts)

  def delete_all(queryable, opts) do
    queryable
    |> first
    |> Repo.one()
    |> case do
      %{__struct__: ZB.Subscription} -> Repo.update_all(queryable, set: [canceled_at: utc_now()])
      _ -> super(queryable, opts)
    end
  end
```

**Comment by atomkirk** [comment]
This was my bad design as a beginner to try and deal with soft delete columns. We've almost moved away from this obviously bad idea but we have one last schema using it.

The reason this was necessary was because ecto doesn't provide any kind of hooks into how it handles `has_many`, `replace_all` with `cast_assoc`. All of those ecto association tools offer a ton of benefits, so we wanted to be able to use them with soft deletes.

I think this is our own problem to solve. Thanks for your quick response :)
