### ISSUE TITLE
Query in association error: "field does not exist" in wrong schema

### ISSUE THREAD

**Issue by gmile** [elixir-ecto/ecto#2838]
I'm having trouble using query in association, along with another `through` association. The reproduction app is available here: https://github.com/gmile/ecto_assoc_query_issue.

Given this setup:

```elixir
defmodule Author do
  use Ecto.Schema

  schema "authors" do
    field(:full_name, :string)
  end
end

defmodule Comment do
  use Ecto.Schema

  import Ecto.Query

  schema "comments" do
    # state is supposed to be: "pending", "approved", "disapproved"
    field(:state, :string)
    field(:post_id, :integer)

    belongs_to(:author, Author)
  end

  def moderated_comments do
    dynamic([c], c.state in ^["approved", "disapproved"])
  end
end

defmodule Post do
  use Ecto.Schema

  schema "posts" do
    field(:title, :string)

    has_many(:moderated_comments, Comment, where: {Comment, :moderated_comments, []})
    has_many(:commenters, through: [:moderated_comments, :author])
  end
end
```

### Current behavior

This code works:

```elixir
query = from(p in Post, join: c in assoc(p, :moderated_comments))

EctoAssocQueryIssue.Repo.all(query)
```

This code:

```elixir
query = from(p in Post, join: c in assoc(p, :commenters))

EctoAssocQueryIssue.Repo.all(query)
```

Raises this error:

```
** (Ecto.QueryError) deps/ecto/lib/ecto/query/planner.ex:18: field `state` in `join` does not exist in schema Author in query:

from p in Post,
  join: a in Comment,
  on: a.state in ^["approved", "disapproved"] and a.post_id == p.id,
  join: c in Author,
  on: c.id == a.author_id,
  select: p

    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1418: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/code.ex:232: Code.eval_string/3
    (elixir) lib/enum.ex:765: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:765: Enum.each/2
    (mix) lib/mix/tasks/run.ex:142: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
```

From the error output above Ecto _seems_ to have generated the query struct properly, e.g. this piece `a.state in ^["approved", "disapproved"] and a.post_id == p.id` was built perfectly correctly, hence the opened issue.

Somehow, if the "association with query" is in the middle of join, things go bad. Am I running into an issue covered by this note [here](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L686)?

### Expected behavior

The SQL query string is produced and sent to DB **or** a more specific error message.

<details>
<summary>Environment</summary>

* Elixir version (elixir -v): Elixir 1.7.3
* Database and version: PostgreSQL 10.5,
* Ecto version: 3.0.3
* Database adapter and version: 0.14
* Operating system: macOS 10.12.6 (16G1114)

</details>

**Comment by josevalim** [comment]
Something is definitely weird because we derive the bindings from the association, so the fact we are using `a` for Comment and `c` for Author means something got cross-wired. So yeah, It looks like a bug. You can do `IO.inspect(query, structs: false)` to see how things look internally.

@zachdaniel, could you take a look at this? No problem if you are busy or unavailable. No rush either. :)

**Comment by mpranjic** [comment]
I did some research on this. There's 100 small functions and little things going on, so I'm not confident that this is a way to go, but it solved the problem reported (it is not a fix as it broke some other parts).

First, `IO.inspect` on query from the outside is not helpful, because `assoc` is not unpacked.
I've put the inspect line as as second line in `Ecto.Query.Planner.plan`.

### Invalid mapping

It seems that joins / params index (`ix`) rewriting goes out of sync, here is the output of `query.joins[0].on`:

```Elixir
 %{
  __struct__: Ecto.Query.QueryExpr,
  expr: {:and, [],
    [
      {:in, [],
      [{{:., [], [{:&, [], [2]}, :state]}, [], []}, {:^, [], [0]}]},   <=== HERE
      {:==, [],
      [
        {{:., [], [{:&, [], [2]}, :post_id]}, [], []},
        {{:., [], [{:&, [], [0]}, :id]}, [], []}
      ]}
    ]},
    file: "/home/marin/Projects/ecto/lib/ecto/query/planner.ex",
    line: 18,
    params: [{["approved", "disapproved"], {:in, {1, :state}}}]   <=== HERE
  },
  params: [],
  prefix: nil,
  qual: :inner,
  source: {"comments", Comment}
}
```

sources is as follows:
```Elixir
sources: {{"posts", Post, nil}, {"authors", Author, nil}, {"comments", Comment, nil}},
```

Therefore I concluded that the index in `params` should be `2`, and not `1`.


I fixed it by adding the following function:

```Elixir
  defp rewrite_param_ix({value, {composite, {type_ix, field}}}, ix, last_ix, source_ix, inc_ix) when is_integer(type_ix) do
    {value, {composite, {rewrite_ix(type_ix, ix, last_ix, source_ix, inc_ix), field}}}
  end
```

### Inverted letters

It seems that inversion of letters (`c in Author`, `a in Comment`) is a separate issue.
Every join expression inside `query.joins` has an index `ix` which maps to an index of a source inside `sources`.

This was not respected by the implementation of `Inspect` for `Ecto.Query` so I added the following function inside `ecto/query/inspect.ex`:

```Elixir
  defp collect_sources(%{sources: sources}) when not is_nil(sources) do
    Enum.map(Tuple.to_list(sources), &elem(&1, 1))
  end
```

### This is not a fix

After these changes 6 test cases are failing, but I'm hoping that this sheds some light on what's going on in there, and someone surely knows how to *actually* solve it :).

### Dynamic bindings

I noticed something, I've never used `dynamic` before and I also tried to check if it was used properly.

The following lines produce the same join:
```Elixir
dynamic([c], c.state in ^["approved", "disapproved"])
dynamic([c, _], c.state in ^["approved", "disapproved"])
dynamic([_, c], c.state in ^["approved", "disapproved"])
dynamic([c, _, _], c.state in ^["approved", "disapproved"])
dynamic([_, c, _], c.state in ^["approved", "disapproved"])
dynamic([..., c], c.state in ^["approved", "disapproved"])
dynamic([_, ..., c], c.state in ^["approved", "disapproved"])
dynamic([..., c, _], c.state in ^["approved", "disapproved"])
```

Only this one produces the mapping to `Author` table:
```Elixir
dynamic([_, _, c], c.state in ^["approved", "disapproved"])   <=== c is an Author, not Comment
```

I no longer have a clue how these bindings work :)

**Comment by josevalim** [comment]
Thanks for the updates, we will take a look at as soon as we find some time. Hopefully it is not an intrinsic issue to our implementation but it is actually starting to look like one. :O

**Comment by josevalim** [comment]
I have a fix for this but it will limit how `where` work. I don't think we have an alternative for it. I will write more about it later today.

**Comment by josevalim** [comment]
Fixed here: 776a5238903dc0f7cb6353b49c7c7f07813bffe6

Unfortunately it means the tuple format no longer works and it can't work with joins query.

**Comment by mpranjic** [comment]
Thanks!

Btw, there's a typo in comments + some tests are failing, wanted to send a PR but noticed the ^commit is not merged to master.

**Comment by josevalim** [comment]
Oops, my bad. It should be up now, here is the commit: d707901888c76057435f1399b2e625105b834238
