### ISSUE TITLE
No safe way to require a belongs to association is NOT NULL.

### ISSUE THREAD

**Issue by bencates** [elixir-ecto/ecto#2866]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): MySQL 14.14
* Ecto version (mix deps): 3.0.2
* Database adapter and version (mix deps): mariaex 0.9.1
* Operating system: Pop!_OS 18.04 (Ubuntu derivative)

### Current behavior

Include code samples, errors and stacktraces if appropriate.

Given the following tables:

```elixir
demodule Migrations.CreateParentAndChild do
  use Ecto.Migration

  def change do
    create table(:child) do
    end

    create table(:parent) do
      add :child_id, references(:child), null: false
    end
  end
end
```

and the following schema:

```elixir
defmodule Parent do
  schema "parent" do
    belongs_to :child, Child
  end

  def changeset_id_required(%Parent{} = parent, attrs) do
    parent
    |> cast(attrs, [:child_id])
    |> validate_required([:child_id])
    |> assoc_constraint(:child)
  end

  def changeset_assoc_required(%Parent{} = parent, attrs) do
    parent
    |> cast(attrs, [:child_id])
    |> validate_required([:child])
    |> assoc_constraint(:child)
  end

  def changeset_without_required(%Parent{} = parent, attrs) do
    parent
    |> cast(attrs, [:child_id])
    |> assoc_constraint(:child)
  end
end
```

### Expected behavior

at least one of the following calls should succeed but both fail with a validation error:

```elixir
%Parent{child: child}
|> Parent.changeset_id_required(%{})
|> Repo.insert()
```

```elixir
%Parent{}
|> Parent.changeset_assoc_required(%{child_id: child.id})
|> Repo.insert()
```

meanwhile, this call raises a raw database error (`child_id` cannot be null) instead of a changeset with errors:

```elixir
%Parent{}
|> Parent.changeset_without_required(%{})
|> Repo.insert()
```

There doesn't appear to be a way to mark an association as required that works regardless of whether the association is being set directly or by ID.

Ideally I would expect `cast/3`, `put_assoc/3`, and `cast_assoc/2` to also populate the ID column when they're attempting to populate a `belongs_to` association, but I realize this would be a substantial breaking change.

I think this issue could also be solved by allowing `validate_required/2` to recognize when it was validating a relationship instead of a field and to pass as valid when the association's ID was set even if the association was itself still `nil`.

**Comment by josevalim** [comment]
> There doesn't appear to be a way to mark an association as required that works regardless of whether the association is being set directly or by ID.

Can you please expand on why are you expecting *both* to work? To me those are conflicting definitions. You are expecting it to be set in both places, so they have to be set in both places. If you assume the validation is either coming as an ID or as an association, then it should work, but I don't understand why they need to work across each other (especially because they are different ways to set data with different trade-offs).

**Comment by josevalim** [comment]
@bencates it definitely matters because I think accepting both through the same API could be a security issue. For example, imagine that we allow you pass a `child_id` where you expect a `cast_assoc`. We could potentially open up vectors that allow you to associate with any ID in the system. So the correct here is to have two distinct functions as entry points. Of course they can share all of the code, but they need to be explicit on how they want this association to be validated.

**Comment by bencates** [comment]
> imagine that we allow you pass a child_id where you expect a cast_assoc. We could potentially open up vectors that allow you to associate with any ID in the system

I believe that's only true if you include `:child_id` in the list passed to the parent's `cast/3` call; otherwise it would be ignored. And we already have two entry points.

My actual concern is around validation. I can't seem to figure out a way to safely absorb the underlying database's "`child_id` cannot be null" error that works whether the child's ID is being provided explicitly or implicitly as part of a child record.
