### ISSUE TITLE
Changeset with `updated_at` doesn't work 

### ISSUE THREAD

**Issue by GildedHonour** [elixir-ecto/ecto#2904]
After calling this:

    Repo.update!(MyModel.changeset(my_model, %{updated_at: DateTime.utc_now()}))

`updated_at` contains an old value.

**Comment by josevalim** [comment]
Please do a proper report, as suggested in the issues template. Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Also include how your changeset function is implemented.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by GildedHonour** [comment]
`updated_at` doesn't change

**Comment by josevalim** [comment]
Ecto doesn't generate anything. Please fill in the issues template accordingly, include the proper versions, etc.

**Comment by mpranjic** [comment]
Try  `my_model = Repo.update!(...)`,

**Comment by GildedHonour** [comment]
@mpranjic in the db the value of `updated_at` remains the same

**Comment by OvermindDL1** [comment]
Just to verify since the `MyModel.changeset` function hasn't been posted (that would really help!), but `:updated_at` is in the `|> cast(attrs, [..., :updated_at])` or otherwise manually cast in the changeset yes?

**Comment by GildedHonour** [comment]
No, `updated_at` it's not in `cast(...)`. And it's so by default.

**Comment by OvermindDL1** [comment]
> No, `updated_at` is not in `cast(...)`.

Ah, that would be why then.  :-)
That's why jose asked for the changeset function code, it's a good first sign to make sure it's actually being cast first.  :-)

> `otherwise manually cast in the changeset yes?` -- how?

The same way, just `changeset = Ecto.Changeset.cast(changeset, %{updated_at: whenever}, [:updated_at])` or something like that, the same thing the changeset function should be doing.

**Comment by josevalim** [comment]
@GildedHonour so you should either add `:updated_at` to the cast list or call `put_change(changeset, :updated_at, DateTime.utc_now)` to store the value dynamically. The default code Phoenix generates will always make some assumptions, if you don't like them, then you have to change them.

Meanwhile, I will go ahead and close this issue. The next time around, please include all the relevant information in the issue template, otherwise we will summarily close it. Also please note that the issues tracker is not a place for questions. This information and alternatives is also listed in the issues template. Thanks.
