### ISSUE TITLE
`Repo.transaction(multi)` doesn't work with dynamic repos

### ISSUE THREAD

**Issue by bartekupartek** [elixir-ecto/ecto#2961]
### Environment

* Ecto version (mix deps): 3.1.0

### Current behavior

`Repo.put_dynamic_repo(:hospital1)` and `Repo.transaction(multi)`  doesn't get the repo module but process name.

```
stacktrace:
       :hospital1.insert(#Ecto.Changeset<action: :insert, changes: %{amount: #Decimal<100>, amount_paid: 66, doctor: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #SecretApp.Doctor<>, valid?: true>, payments: [#Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #SecretApp.Patient.Payment<>, valid?: true>, #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #SecretApp.Patient.Payment<>, valid?: true>], provider: #Ecto.Changeset<action: :update, changes: %{}, errors: [], data: #SecretApp.Billing.Provider<>, valid?: true>}, errors: [], data: #SecretApp.Patient.ClaimsApplication<>, valid?: true>, [])
       (ecto) lib/ecto/multi.ex:579: Ecto.Multi.apply_operation/5
       (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto) lib/ecto/multi.ex:563: anonymous fn/5 in Ecto.Multi.apply_operations/5
       (ecto_sql) lib/ecto/adapters/sql.ex:875: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection) lib/db_connection.ex:1415: DBConnection.run_transaction/4
       (ecto) lib/ecto/repo/transaction.ex:16: Ecto.Repo.Transaction.transaction/3
       (secret_app) lib/secret_app/patient/claim_forms.ex:89: SecretApp.Patient.ClaimForms.apply_claim_forms_payments/1
       test/lib/finance/claim_forms_test.exs:191: (test)
```

**Comment by josevalim** [comment]
Awesome! Can you please provide a failing test case and possibly a PR with
a fix? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by iautom8things** [comment]
@josevalim I'm sorry to bring up an issue from 3 years ago, but the title is exactly the issue that I'm having, but it appears a change made in https://github.com/elixir-ecto/ecto/commit/1f9c4c1e69f975d3663ec6b88295cba71bd0e4b3, at least anecdotally, may be the cause of my issue:

I'm following the convention specified in the docs (https://hexdocs.pm/ecto/replicas-and-dynamic-repositories.html#dynamic-repositories) for working with dynamic repositories for my use case of multi-tenant databases.  And I'm trying to utilize a `Ecto.Multi` run in a transaction.  So this looks something like:

```elixir
MyApp.Repo.with_dynamic_repo(tenant1_creds, fn ->
  Multi.new |> Multi.run(:for_tenant, query(" ...")) |> MyApp.Repo.transaction()
end)
```

The problem is that this transaction runs against the default database credentials set up with that particular repo module ... it's as if executing the transaction is ignoring the dynamic repo that is being set.


If I undo this change in `deps/ecto/lib/ecto/repo/transaction.ex:16` [here](https://github.com/elixir-ecto/ecto/commit/1f9c4c1e69f975d3663ec6b88295cba71bd0e4b3#diff-1e0793066e56f0689034c5b6bca68d86657a271d17de1938b49fafd4d2bef371L16):

```elixir
case Ecto.Multi.__apply__(multi, name, wrap, return) do
```

It works -- it uses the dynamic repo.

This is my first time delving into the internals of ecto.  I'd be happy to try to help provide any more information, or even can send a PR if this is the proper fix.  Thank you!

**Comment by josevalim** [comment]
Hi @iautom8things ! Do you think you can write a test case in ecto_sql? Check out the steps in this README. If you can reproduce it, then that’s the first step for a fix!

**Comment by iautom8things** [comment]
I'll give it a try.  Thank you 🙇

**Comment by iautom8things** [comment]
@josevalim elixir-ecto/ecto_sql#386 is my attempt to write a test to demonstrate this issue.

**Comment by josevalim** [comment]
Quick answer: this will if you use `repo.query(...)` instead of `Ecto.Adapters.SQL.query`. The latter is by passing the dynamic repo  lookup.

**Comment by iautom8things** [comment]
Thank you, @josevalim.  That does fix my issue.  I'm honestly not sure why I was using `Ecto.Adapters.SQL` in the first place. >_<
