### ISSUE TITLE
Search engine does not find documentation for functions like where, from, and, or.

### ISSUE THREAD

**Issue by sztosz** [elixir-ecto/ecto#2972]
### Current behaviour

https://hexdocs.pm/ecto/search.html?q=where gives no results "Sorry, we couldn't find anything for with.

https://hexdocs.pm/ecto/search.html?q=from gives no results "Sorry, we couldn't find anything for with.

https://hexdocs.pm/ecto/search.html?q=or gives no results "Sorry, we couldn't find anything for with.

https://hexdocs.pm/ecto/search.html?q=and finds only one result: https://hexdocs.pm/ecto/Ecto.Query.html#or_where/3

### Expected behaviour

https://hexdocs.pm/ecto/search.html?q=where should find at least this page: https://hexdocs.pm/ecto/Ecto.Query.html#where/3

https://hexdocs.pm/ecto/search.html?q=or should find at least this page: https://hexdocs.pm/ecto/Ecto.Query.API.html#or/2

https://hexdocs.pm/ecto/search.html?q=and should also find this page: https://hexdocs.pm/ecto/Ecto.Query.API.html#and/2

https://hexdocs.pm/ecto/search.html?q=from should find at least this page:  https://hexdocs.pm/ecto/Ecto.Query.html#from/2

My suspicion is that may be a bug in ex_doc itself but I simply don't know how to check it.

**Comment by josevalim** [comment]
It is definitely a bug in ExDoc. Can you please open up the issue there?

But it may be that we can't fix it in all cases. Words like `and` and `or` are usually removed from full text search engines because they are considered stop words. We could remove the stop words and keep `and` and `or` but they will likely appear on *every* result.

Maybe a course of action is to add a new entry to the search suggestions that say "If you are looking for a particular module or function, use the autocompletion feature in the sidebar search, instead of full-text search."

**Comment by sztosz** [comment]
Opened issue in ex_doc https://github.com/elixir-lang/ex_doc/issues/996
