### ISSUE TITLE
Unexpected logging when running tests

### ISSUE THREAD

**Issue by novaugust** [elixir-ecto/ecto#2978]
### Environment

* Elixir version (elixir -v): 1.7.4
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): psql 11.2
* Ecto version (mix deps):  3.1.1
* Database adapter and version (mix deps):  ecto_sql 3.1.1
* Operating system: macos

### Current behavior

after upgrading ecto 3.0 -> 3.1, i’m seeing unexpected logs when running tests, like

```
2019-04-16 15:32:27.472 MDT [49856] ERROR:  update or delete on table "..." violates foreign key constraint "...." on table "..."
2019-04-16 15:32:27.472 MDT [49856] DETAIL:  Key (id)=(...) is still referenced from table "...".
2019-04-16 15:32:27.472 MDT [49856] STATEMENT:  DELETE FROM ... WHERE "id" = $1
```

### Expected behavior

These logs should be routed through the logger application, and so not printed to the console (thanks to config settings)

**Comment by josevalim** [comment]
If they are being printed with such timestamps... then they are being routed through the logger, no? Or does it just look like Logger's? 

In any case, I agree this should not happen, do you have a way to reproduce this bug? Thank you.

**Comment by novaugust** [comment]
Seems like any sort of psql error will trigger it. Easiest repro:

1. clone bare-bones phx app https://github.com/novaugust/ecto-concurrent-index-bug
2. `mix ecto.create`
3. repeat `mix ecto.create`
```
➜  ecto-concurrent-index-bug git:(master) mix ecto.create
2019-04-16 16:19:26.798 MDT [56432] ERROR:  database "hello_dev" already exists
2019-04-16 16:19:26.798 MDT [56432] STATEMENT:  CREATE DATABASE "hello_dev" ENCODING 'UTF8'
The database for Hello.Repo has already been created
```

**Comment by josevalim** [comment]
Unfortunately I cannot reproduce this:

```
~/OSS/ecto-concurrent-index-bug[master]$ mix ecto.create
The database for Hello.Repo has already been created
~/OSS/ecto-concurrent-index-bug[master]$ mix ecto.create
The database for Hello.Repo has already been created
```

Any idea why it happens locally for you? I couldn't find anywhere where we would be logging those messages as they have been formatted for you.

**Comment by josevalim** [comment]
Possibly question: could you have started postgres as a background process attached to your current terminal and those logs are coming for postgres?

**Comment by novaugust** [comment]
Given that I also reinstalled + upgraded psql to 11 at the same time I did this 3.1 migration, something like that seems a likely culprit. Especially given the lack of repro =) 
I'll twiddle with my environment, thanks for the prompt help

**Comment by lancejjohnson** [comment]
@novaugust I was recently coming across the same issue. Jose's comments led me (and some friends helping me out) to look into how I was starting the postgres server. I had been using `pg_ctl` to start the server when I received a connection error when trying to run my tests. I shut down the server and switch to using `brew services start postgresql` and the errors no longer appear in my terminal when running tests. Just thought I would comment here as this issue led me toward the solution.

**Comment by nicnilov** [comment]
This is a documented behaviour, manifesting itself when starting postgres via `pg_ctl` without any explicit output control:

From [`pg_ctl` docs](https://www.postgresql.org/docs/current/app-pg-ctl.html#APP-PG-CTL-DESCRIPTION):
> On Unix-like systems, by default, the server's standard output and standard error are sent to pg_ctl's standard output (not standard error). The standard output of pg_ctl should then be redirected to a file or piped to another process such as a log rotating program like rotatelogs; otherwise postgres will write its output to the controlling terminal (from the background) and will not leave the shell's process group. On Windows, by default the server's standard output and standard error are sent to the terminal. These default behaviors can be changed by using -l to append the server's output to a log file. Use of either -l or output redirection is recommended.

The solution with `brew services start postgresql` works because the service definition file includes log redirection directives:

From `/usr/local/opt/postgresql@11/homebrew.postgresql@11.service` (only the relevant bits):

```
[Service]
ExecStart=/usr/local/opt/postgresql@11/bin/postgres -D /usr/local/var/postgresql@11
StandardOutput=append:/usr/local/var/log/postgresql@11.log
StandardError=append:/usr/local/var/log/postgresql@11.log
```

If it is desirable to still use `pg_ctl`, there are several solutions:

1. Pass the `-l` flag to `pg_ctl`, specifying the log output location:

```
pg_ctl -D /usr/local/var/postgresql@11 -l /usr/local/var/log/postgresql@11.log start
```

2. Redirect the log output explicitly:

```
pg_ctl -D /usr/local/var/postgresql@11 start > pglog.log
```

3. Use the [`logging_collector` setting](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOGGING-COLLECTOR) in the `postgresql.conf` file:

```
# This is used when logging to stderr:
logging_collector = on  # Enable capturing of stderr and csvlog
                        # into log files. Required to be on for
                        # csvlogs.
                        # (change requires restart)
```

In this case postgres should be started with a simple `pg_ctl -D /usr/local/var/postgresql@11 start`, and the log by default will be redirected to a file under the data directory's `log` subdirectory, e.g. `/usr/local/var/postgresql@11/log/postgresql-2022-05-07_002430.log`. The destination can be configured by the nearby settings in the same file.
