### ISSUE TITLE
Updating the id from an association from nil to some id doesn't reset the association 

### ISSUE THREAD

**Issue by tarzan** [elixir-ecto/ecto#3007]
### Environment

* Elixir version (elixir -v): 1.8.1
* Database and version (PostgreSQL 11.2):
* Ecto version (mix deps): 3.1.4
* Database adapter and version (mix deps): ecto_sql 3.1.3
* Operating system: MacOS

### Current behavior

When updating the :id of an association from nothing to something, the resulting struct has the association still on `nil` instead of `#Ecto.Association.NotLoaded`, making it impossible to (Repo.)preload on it.

Considering the following schema:
```ex
schema "pull_requests" do
  field(:content, :string)
  field(:approved, :boolean, default: false)

  belongs_to(:created_by, User)
  belongs_to(:reviewed_by, User)
end
```
and the following changeset function:
```ex
def changeset(%PullRequest{} = pr, attrs, %User{} = actor) do
  pr
  |> cast([:approved, :content])
  |> set_updated_by(actor)
end 

defp set_updated_by(%Changeset{data: %PullRequest{id: id}} = changeset, %User{id: user_id}) when not is_nil(id) do
  changeset
  |> put_change(:reviewed_by_id, user_id)
  |> assoc_constraint(:reviewed_by)
  |> foreign_key_constraint(:reviewed_by_id)
end
```

and doing the following:
```ex
iex> pr = Repo.get(PullRequest, 5)
%PullRequest{
  id: 5,
  content: "some content",
  approved: false,
  created_by: #Ecto.Association.NotLoaded<...>,
  created_by_id: 1,
  reviewed_by: nil,
  reviewed_by_id: nil
}

iex> changeset = PullRequest.changeset(pr, %{approved: true}, %User{id: 9}) 
#Ecto.Changeset<
  action: nil,
  changes: %{approved: true, reviewed_by_id: 9},
  errors: [],
  data: #PullRequest<>,
  valid?: true
>

iex> {:ok, updated_pr} = Repo.update(changeset)
{:ok, %PullRequest{
  id: 5,
  content: "some content",
  approved: true,
  created_by: #Ecto.Association.NotLoaded<...>,
  created_by_id: 1,
  reviewed_by: nil,
  reviewed_by_id: 9
}

iex> Repo.preload(updated_pr, :reviewed_by)
%PullRequest{
  id: 5,
  content: "some content",
  approved: true,
  created_by: #Ecto.Association.NotLoaded<...>,
  created_by_id: 1,
  reviewed_by: nil,
  reviewed_by_id: 9
}
```
### Expected behavior
```ex
iex> Repo.update(changeset)
{:ok, %PullRequest{
  id: 5,
  content: "some content",
  approved: true,
  created_by: #Ecto.Association.NotLoaded<...>,
  created_by_id: 1,
  reviewed_by: #Ecto.Association.NotLoad<...>,
  reviewed_by_id: 9
}

iex> Repo.preload(updated_pr, :reviewed_by)
%PullRequest{
  id: 5,
  content: "some content",
  approved: true,
  created_by: #Ecto.Association.NotLoaded<...>,
  created_by_id: 1,
  reviewed_by: %User{id: 9},
  reviewed_by_id: 9
} 
```

**Comment by josevalim** [comment]
I am not sure if there is something Ecto could fix here. Since you have two sources of truth, the association and the foreign key, Ecto can't know what it is the correct one. We could assume the association is outdated, but perhaps someone did the opposite and updated the association while keeping the foreign key.

My suggestion is for you to put `put_change(:reviewer_by, user)` instead of setting the ID directly. Otherwise it would be quite hard for Ecto to know the association is the one invalid once the ID changes (or vice-versa).

**Comment by tarzan** [comment]
Thanks for you swift response! I will try your suggestion. Another way to solve this seems to be to `Repo.preload/3` with option `force: true`, but that feels a bit heavy for my taste.

However I don't really understand you objection of there being 2 sources of truth. As far as I can see, there's only one: the changes proposed in the changeset, ie. when the foreign key is being changed the struct should reset the association upon applying changes and when the association is being changed it's id should replace the existing one on struct. Am I missing something here?

**Comment by josevalim** [comment]
Well, associations are built on top of fields, so while associations know about fields, fields don't know about associations.

Even if we could change this, the reason why we don't generally change the association once you change the field is because this won't generally work for other associations. For example, imagine Post has many comments, I have a Post with loaded comments, and then I change the Post ID. This should theoretically clear all comments, because they may be pointing elsewhere now. So if we allow users to have the assumption that changing fields will expire data, this assumption will always break at some point, as the data graph can get really complex.

**Comment by tarzan** [comment]
I get that complexity grows with the amount of associations within one's domain. 

However, considering your example doesn't make much sense to me as updating an (primary) ID on a record feels like something someone should never want or do. It's there to uniquely identify the record in the first place, right?

I also think that `belongs_to` and `has_many` should be handled separately. Only considering `belongs_to` here should reduce the number of possible scenario's considerably I would say.

I experimented briefly with `put_change(:reviewed_by, user)` over `put_change(:reviewed_by_id, user)`, but that only works if the current association is actually (nil or a user) otherwise Ecto returns an error. 

Anyhow, what happens under the hood is that the returned fields from the database are being merged in the feed struct? Can't we manipulate this merge by looking at returned foreign keys that are different from the ones in the original struct and then invalidation its preloads?

**Comment by josevalim** [comment]
> I experimented briefly with put_change(:reviewed_by, user) over put_change(:reviewed_by_id, user), but that only works if the current association is actually (nil or a user) otherwise Ecto returns an error.

Right, but in your case the data is there. Which is why you are running into this issue in the first place, isn't?

**Comment by tarzan** [comment]
> > I experimented briefly with put_change(:reviewed_by, user) over put_change(:reviewed_by_id, user), but that only works if the current association is actually (nil or a user) otherwise Ecto returns an error.
> 
> 
> Right, but in your case the data is there. Which is why you are running into this issue in the first place, isn't it?

Yes it is in the actual code, but I didn't notice at first because all written tests were passing. The difference between manually created structs that have the association unloaded and the actual production code that used fully preloaded structs.

**Comment by tarzan** [comment]
If I would work on a PoC for solving this problem specifically for updating belongs_to relations, would you take it into consideration? or do you think it has a high chance to be dismissed anyhow?

**Comment by josevalim** [comment]
We have generally avoided adding behaviour that is specific to certain associations. Also, as I said above, we also have this issue on has_one/has_many.

Although the example I used previously used the primary key, it doesn't have to be the primary key in practice. And changing the primary key is only messy if using auto-incrementing keys, otherwise it can happen without issues.

So in a nutshell, I am not saying we shouldn't do this, but I think adding it only for belongs_to would be undesirable.

Perhaps a simpler and more consistent change is to allow you to call `put_assoc(...)` even if the association was not loaded, as long as the `on_replace` strategy of that association is `:nothing`.

**Comment by josevalim** [comment]
Closing this for the reasons above. Thanks!
