### ISSUE TITLE
datetime_add truncates timezone data when using utc_datetime timestamps and timestamptz columns

### ISSUE THREAD

**Issue by dkulchenko** [elixir-ecto/ecto#3084]
### Environment

* Elixir version (elixir -v): 1.9.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 11.4
* Ecto version (mix deps): ecto 3.2.0-dev (f41c569), but happens on the latest stable as well
* Database adapter and version (mix deps): postgrex 0.15.0
* Operating system: Ubuntu 18.04 LTS

### Current behavior

With timestamps configured as `utc_datetime` in the schema and created as `timestamptz` in the migration, the following code

```
from(req in Request,
      where: req.status == "pending",
      where:
        datetime_add(
          req.inserted_at,
          ^max_delay,
          "minute"
        ) < DateTime.utc_now()
    )
```

gets translated to the query:

```
SELECT i0."id", i0."account_id", i0."request_id", i0."status", i0."inserted_at", i0."updated_at" FROM "requests" AS i0 WHERE (i0."status" = 'pending') AND (i0."inserted_at"::timestamp + ($1::numeric * interval '1 minute') < $2) [#Decimal<5>, ~N[2019-08-13 00:16:00]]
``` 

Due to the ::timestamp cast, my inserted_at timestamptz which is "2019-08-12 17:10:31-07" in the database is being truncated to "2019-08-12 17:10:31" in the query, rather than what it likely should have been cast to, which is "2019-08-13 00:10:31".

### Expected behavior

I would expect datetime_add to respect the fact that the inserted_at timestamp is a timestamptz and not ignore the tz info during the addition, leading to incorrect math.

In query terms, when inserted_at is a timestamptz type, the query should probably be `(i0."inserted_at" at time zone 'UTC')::timestamp` for Postgres in this situation rather than `i0."inserted_at"::timestamp`.

**Comment by josevalim** [comment]
Ecto doesn't know anything about timestamptz. We also don't know what is the type in the database. I tried to do `(i0."inserted_at" at time zone 'UTC')::timestamp` but it started returning the wrong offsets in our test suite.

Therefore, the only solution I have in mind is that you have to explicitly tell Ecto the type:

```elixir
datetime_add(
  type(req.inserted_at, TypeWithTimeZone),
  ^max_delay,
  "minute"
)
```

and `TypeWithTimeZone` is a custom Ecto type. Libraries like Calecto ship with said types. You will need `ecto_sql` master for it to work.

Thanks for the report!

**Comment by michalmuskala** [comment]
What is the Ecto type of the inserted_at field? If it's utc_datetime it shouldnt have a value with an offset in the first place. We should probably error if such a value of provided to the dump function.

**Comment by dkulchenko** [comment]
@josevalim I'll give that a try, thanks! It just feels weird to have to do that though (see below).

@michalmuskala Yeah, inserted_at is indeed a utc_datetime (being defined via `timestamps(type: :utc_datetime)`). On insertion, the query is:

`INSERT INTO "requests" ("account_id","request_id","status","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4,$5,$6,$7) [<<89, 24, 120, 219, 58, 225, 64, 101, 188, 38, 217, 11, 245, 83, 166, 240>>, <<47, 124, 5, 216, 227, 39, 66, 145, 129, 20, 52, 29, 255, 79, 204, 87>>, "pending", ~U[2019-08-13 17:28:16Z], ~U[2019-08-13 17:28:16Z], <<136, 251, 247, 145, 29, 43, 72, 223, 164, 41, 142, 214, 80, 67, 241, 165>>]
`

So judging from the ~U sigil, the timestamps are being persisted/read directly as a DateTime with no offset or casting so there is no mismatch on inserts/writes. But datetime_add on the same field performs the ::timestamp cast:

`
SELECT r0."id", r0."account_id", r0."request_id", r0."status", r0."inserted_at", r0."updated_at" FROM "requests" AS r0 WHERE (r0."status" = 'pending') AND (r0."inserted_at"::timestamp + ($1::numeric * interval '1 minute') < $2) [#Decimal<5>, ~N[2019-08-13 00:16:00]]
`

which leads to the issue. Maybe the ::timestamp cast should be removed entirely? 

Is it casting because the `<` comparison is to a NaiveDateTime? But if so, why is `DateTime.utc_now()` being sent as a NaiveDateTime into the latter query (~N sigil in the SELECT) when the INSERT above receives it as a DateTime?

**Comment by jyc** [comment]
I'm wary of necroing this thread, but I ran into it while debugging almost exactly the same issue in my own codebase.

I had a very similar query (`ready_at < ^DateTime.utc_now()`) that Ecto was compiling to `h0."ready_at" < '2024-07-30 23:23:45.442135Z'::timestamp`. On macOS [Postgres.app](https://postgresapp.com/) appears to set the default session timezone to `timezone = 'America/Los_Angeles'` in `/Users/jyc/Library/Application Support/Postgres/var-16/postgresql.conf`, so this query was creating a bug by comparing two timestamps where one was always offset 7 hours into the future.

The fix I ended up doing was to ask Ecto to set the session timezone to UTC whenever it connects to Postgres:

```
config :foo, Foo.Repo
  after_connect: {Postgrex, :query!, ["SET TIME ZONE 'UTC'"]}
```

This seems to have fixed the issue for good; I didn't have to change any of my queries. IMO it would be pretty cool if this were the default in Phoenix or even Ecto, just because it seems like it avoids a footgun. But I understand if it's extraneous for most usecases. I was pretty surprised to find that my database's default timezone was set to `America/Los_Angeles` in the first place.
