### ISSUE TITLE
Error with merge_select or map update syntax in subquery

### ISSUE THREAD

**Issue by futpib** [elixir-ecto/ecto#3129]
### Environment

* Elixir version (elixir -v): Elixir 1.9.0 (compiled with Erlang/OTP 22)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Any
* Ecto version (mix deps): 3.1.7 and `master`
* Database adapter and version (mix deps): Any
* Operating system: Linux

### Current behavior

```elixir
from(
	subquery(
		from(p in Post)
		|> select_merge([p], %{ extra_field: p.title + p.text })
	)
)
```

When trying to execute a query like this (or even just run `Ecto.Query.Planner.plan` on it) I get the following error:

```
     ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.
     
         ** (KeyError) key :extra_field not found in: %Ecto.Query.SubqueryTest.Post{__meta__: #Ecto.Schema.Metadata<:built, "posts">, comments: #Ecto.Association.NotLoaded<association :comments is not loaded>, id: {:value, Custom.Permalink}, text: {:value, :string}, title: {:value, :string}}
     
     The subquery originated from the following query:
     
     from p0 in subquery(from p0 in Ecto.Query.SubqueryTest.Post,
       select: merge(p0, %{extra_field: p0.title + p0.text}))
```

Here is a PR with the failing test: #3128.

If I remove a layer of subquery like this, I do not get an error:

```elixir
from(p in Post)
|> select_merge([p], %{ extra_field: p.title + p.text })
```

If instead of using `select_merge` I manually enumerate every field from the schema in a map, I do not get an error. This is the workaround I'm settling with for now:

```elixir
from(
	subquery(
		from(p in Post)
		|> select([p], %{ 
			id: p.id,
			title: p.title,
			text: p.text,
			extra_field: p.title + p.text
		})
	)
)
```

A different error happens if I use `select` with map update syntax in a subquery instead of `select_merge`: `select([p], %{ p | extra_field: p.title + p.text })`. This may be a different issue, but I thought I had to mention this.

### Expected behavior

Ecto allows for `select_merge` (and map update syntax) in `subquery` or throws a better error.

**Comment by Eiji7** [comment]
Ok, I made a small research …

The story begins here:

https://github.com/elixir-ecto/ecto/blob/052a9eb4985fdf678362d20ec1f1aba3bc7cfd16/lib/ecto/query/planner.ex#L263-L287

As you can see in this part there is nested call to `subquery_select/3`. In this we are checking if there are 2 different structs (which is not our use case). The important part of this check is that we all those cases:

1. 2 maps
2. map + struct
3. struct + map

1st point is also not our use case as its later pattern-matched in another function clausule.

Our use case is **any** of 2nd or 3rd point. In both cases we have `expr` (after such nested call) set to `{:%, [], [struct, {:%{}, [], fields}]} `.

Now please take a look at 2nd quoted code part:
https://github.com/elixir-ecto/ecto/blob/052a9eb4985fdf678362d20ec1f1aba3bc7cfd16/lib/ecto/query/planner.ex#L1222-L1226

After collecting keyword we are forcing to create struct or raise!

Here is an hidden exception:

```elixir
%KeyError{
  key: :extra_field,
  message: nil,
  term: %Ecto.Query.SubqueryTest.Post{
    __meta__: #Ecto.Schema.Metadata<:built, "posts">,
    comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
    id: {:value, Custom.Permalink},
    text: {:value, :string},
    title: {:value, :string}
  }
}
```
and here is a `__STACKTRACE__`:
```elixir
[
  {:maps, :update,
   [
     :extra_field,
     {:value, :any},
     %Ecto.Query.SubqueryTest.Post{
       __meta__: #Ecto.Schema.Metadata<:built, "posts">,
       comments: #Ecto.Association.NotLoaded<association :comments is not loaded>,
       id: {:value, Custom.Permalink},
       text: {:value, :string},
       title: {:value, :string}
     }
   ], []},
  {Ecto.Query.SubqueryTest.Post, :"-__struct__/1-fun-0-", 2,
   [file: 'test/ecto/query/subquery_test.exs', line: 26]},
  {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1948]},
  {Kernel, :struct!, 2, [file: 'lib/kernel.ex', line: 2147]},
  {Ecto.Query.Planner, :collect_fields, 5,
   [file: 'lib/ecto/query/planner.ex', line: 1224]},
  {Ecto.Query.Planner, :subquery_select, 2,
   [file: 'lib/ecto/query/planner.ex', line: 274]},
  {Ecto.Query.Planner, :plan_source, 3,
   [file: 'lib/ecto/query/planner.ex', line: 233]},
  {Ecto.Query.Planner, :plan_from, 2,
   [file: 'lib/ecto/query/planner.ex', line: 224]},
  {Ecto.Query.Planner, :plan_sources, 2,
   [file: 'lib/ecto/query/planner.ex', line: 213]},
  {Ecto.Query.Planner, :plan, 3, [file: 'lib/ecto/query/planner.ex', line: 198]},
  {Ecto.Query.SubqueryTest, :normalize_with_params, 2,
   [file: 'test/ecto/query/subquery_test.exs', line: 42]},
  {Ecto.Query.SubqueryTest, :normalize, 2,
   [file: 'test/ecto/query/subquery_test.exs', line: 38]},
  {Ecto.Query.SubqueryTest,
   :"test normalize: merges subqueries schema fields with map fields", 1,
   [file: 'test/ecto/query/subquery_test.exs', line: 292]},
  {ExUnit.Runner, :exec_test, 1, [file: 'lib/ex_unit/runner.ex', line: 355]},
  {:timer, :tc, 1, [file: 'timer.erl', line: 166]},
  {ExUnit.Runner, :"-spawn_test_monitor/4-fun-1-", 4,
   [file: 'lib/ex_unit/runner.ex', line: 306]}
]
```

You can confirm it by replacing this line:
https://github.com/elixir-ecto/ecto/blob/052a9eb4985fdf678362d20ec1f1aba3bc7cfd16/lib/ecto/query/planner.ex#L237
with this code:
```elixir
      e -> IO.inspect(e); IO.inspect(__STACKTRACE__); raise Ecto.SubQueryError, query: query, exception: e
```

I'm not following `ecto` source code, so I'm not sure in which place exactly is bug, so here are 2 my propositions:

1. `expr` in 1st code quote is wrong and therefore we are using bad function clausule for such use case.
I did not take a look at all of them, but I saw other clausule which worked on `AST` for maps. The only downside is that we would always return map regardless if we are merging with only struct keys or with extra keys. While it should work I'm not sure if it's not a breaking change.

2. The bug is in 2nd code quote and code should be changed there.
I'm not sure about it, because other code may use this clausule too.

@josevalim I could take a deeper look a bit later and share my thoughts if you wish.

**Comment by Eiji7** [comment]
@josevalim I know that lots of people are busy around logger topic, but there is no response for about week (to my reply) and more than month (for this issue at all). As said at end I'm not sure which of those 2 points is correct. If I would get a hint of what is expected here then I would be able to make a PR for that, but since I'm not familiar with planner I'm not sure which way of code change would be best in this case.

**Comment by josevalim** [comment]
Hi @Eiji7! In this case, just a ping would have sufficed, because what most likely happened is that I just missed your comment. And regarding the issue as a whole, I didn't comment because I didn't have time to investigate it.

BUT you did have time, which is fantastic and very appreciated, so my reply is below.

In a nutshell, I think the error is correct. We can't `select_merge` a field that doesn't exist into a Post struct, because then the Post would become invalid. So subquery is behaving as expected! The question is why `from(p in Post) |> select_merge([p], %{ extra_field: p.title + p.text })`, without the subquery, is not raising. And it may be raising after all, it just happens that it raises only when the query is executed (it is a deferred check).

**Comment by josevalim** [comment]
So I did a check and the regular query does raise when executed:

```
  1) test from: subqueries with select source (Ecto.Integration.SubQueryTest)
     integration_test/sql/subquery.exs:9
     ** (ArgumentError) struct %Ecto.Integration.Post{__meta__: #Ecto.Schema.Metadata<:loaded, "posts">, author: #Ecto.Association.NotLoaded<association :author is not loaded>, author_id: nil, bid: nil, comments: #Ecto.Association.NotLoaded<association :comments is not loaded>, comments_authors: #Ecto.Association.NotLoaded<association :comments_authors is not loaded>, comments_authors_permalinks: #Ecto.Association.NotLoaded<association :comments_authors_permalinks is not loaded>, constraint_users: #Ecto.Association.NotLoaded<association :constraint_users is not loaded>, cost: nil, counter: nil, id: 8, inserted_at: ~N[2019-11-02 09:40:16], intensities: nil, intensity: nil, links: nil, meta: nil, permalink: #Ecto.Association.NotLoaded<association :permalink is not loaded>, post_user_composite_pk: #Ecto.Association.NotLoaded<association :post_user_composite_pk is not loaded>, posted: nil, public: true, temp: "temp", text: "hello", title: nil, unique_users: #Ecto.Association.NotLoaded<association :unique_users is not loaded>, update_permalink: #Ecto.Association.NotLoaded<association :update_permalink is not loaded>, updated_at: ~N[2019-11-02 09:40:16], users: #Ecto.Association.NotLoaded<association :users is not loaded>, users_comments: #Ecto.Association.NotLoaded<association :users_comments is not loaded>, uuid: "612ffe3b-3e25-4d34-ba5f-bda390551a71", visits: nil} does not have the key :extra_field
     code: |> TestRepo.all
```

So everything is behaving as expected. The reason we can do the compile checking for subquery is that subqueries only allow a limited set of expressions. `select` is more generic, so we check when executing.

The solution is to return a tuple or a map with both post and extra_field keys.

Thanks @futpib for reporting and the failing test and thanks @Eiji7 for the investigation.
