### ISSUE TITLE
Safe LIKE / ILIKE

### ISSUE THREAD

**Issue by dbi1** [elixir-ecto/ecto#3222]
Hello,

any chance for a version of the like / ilike functions that include protection against like injection? 

It would be a really nice convenience not having to sanitize input before using like / ilike.

Thank you for building Ecto, it is great!

**Comment by josevalim** [comment]
IIRC like/ilike were safe by default but people wanted to actually allow users to use % and the link in the search interface, so we removed it. So now we leave it up for you to escape it yourself, especially because if we were to provide safe versions, a few combinations would be required (safe in prefix, safe in suffix, etc).

**Comment by barttenbrinke** [comment]
I just discovered this was a thing. Wouldn't it make more sense to be safe by default an implement an unsafe() version? Safe by default seems betterhere to me at least.
