### ISSUE TITLE
Put_assoc with many to many doesn't work.

### ISSUE THREAD

**Issue by Adzz** [elixir-ecto/ecto#3274]
### Precheck

👍 

### Environment

* Elixir version (elixir -v): 1.10.2
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres: 12.2
* Ecto version (mix deps): 3.4.0 ecto_sql: 3.4.2
* Database adapter and version (mix deps): postgrex 0.15.3
* Operating system: unix (mac)

### Current behavior

I've made a minimal test repo here: https://github.com/Adzz/postgres_test

Essentially if I try to do an upsert on a many to many relationship, the result of the upsert looks correct,  but if I then query the db, the rows in the join table are still there.

### Expected behavior

This could be user error which would be very embarrassing but it looks like `put_assoc` isn't working? 

this is the relevant code:

```elixir
  def run(%{id: post_id}) do
    Ecto.Changeset.cast(%Post{id: post_id}, %{id: post_id, author: "Mike wazowski"}, [:author])
    |> Ecto.Changeset.put_assoc(:post_tags, [])
    |> Repo.insert(
      returning: true,
      on_conflict: {:replace_all_except, [:id]},
      conflict_target: [:id]
    )
    |> IO.inspect(limit: :infinity, label: "insert result")

    from(p in Post, preload: [:post_tags, :tags])
    |> Repo.all()
    |> IO.inspect(limit: :infinity, label: "Database result")
  end

  def setup do
    post = %{id: post_id} = Repo.insert!(%Post{author: "Mike wazowski"})

    %{id: tag_1_id} = Repo.insert!(%Tag{name: "not great"})
    %{id: tag_id} = Repo.insert!(%Tag{name: "great"})

    Repo.insert!(%PostTag{post_id: post_id, tag_id: tag_1_id})
    Repo.insert!(%PostTag{post_id: post_id, tag_id: tag_id})
    post
  end
```

Here `insert result` looks correct, but `Database result` shows the post_tags still there.

**Comment by josevalim** [comment]
`put_assoc` has to compare the before and after for it to know what to delete. Since you are passing a brand new record, the association is an empty list and when you `put_assoc` with an empty list, Ecto correctly concludes that there is nothing to change in the database.

You could try to pass the existing tags on `insert`, but Ecto works under the assumption there is no previous association at the time of `insert` - which in all cases is a very reasonable assumption to make. What you are trying to achieve is probably more sanely done with using an update operation on the current ID.
