### ISSUE TITLE
"Ecto.Changeset.validate_confirmation(:password, requried: true)" : options "requried: true" not work

### ISSUE THREAD

**Issue by tuan-karma** [elixir-ecto/ecto#3367]
### Environment

* Elixir version (elixir -v): 1.10.4
* Database and version: PostgreSQL 12.3
* Ecto version (mix deps): 3.4.5
* Database adapter and version (mix deps): ecto_sql 3.4.5 
* Operating system: MS Windows 10

### Current behavior
I used "Ecto.Changeset.validate_confirmation(:password, requried: true)" in the changeset but found that the options "required: true" is not in effect.
See the code below:
```elixir 
def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:username, :email_address])
    |> validate_required([:username, :email_address, :hashed_password])
    |> validate_length(:username, min: 3)
    |> unique_constraint(:username)
  end

 def changeset_with_password(user, params \\ %{}) do
    user
    |> cast(params, [:password])
    |> validate_required(:password)
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password, requried: true)
    |> hash_password()
    |> changeset(params)
  end
```
Then "iex -S mix", in the iex console I type an input params as following. *Note that:* **without the password_confirmation** field in the params but the output **valid?: true**.
```elixir 
> User.changeset_with_password(%User{}, %{username: "tuan", email_address: "tuan@example.com", password: "123456"})
#Ecto.Changeset<
  changes: %{
    email_address: "tuan@example.com",
    hashed_password: "$pbkdf2-sha512$160000$7eEgt5relp6xAljPua1W5A$8O.trBPeU0nGShA/5lrRxLiBaKoffkipLKgswwAtZ9g0lVJzomDx69wzVq/r99Crv6OOTsBxaY/1pDbN8WJ1eA",
    password: "123456",
    username: "tuan"
  },
  errors: [],
  data: #Auction.User<>,
  valid?: true
```
### Expected behavior
```elixir
...
errors: [password_confirmation: {"can't be blank", [validation: required]}]
valid?: false
```

**Comment by wojtekmach** [comment]
Per docs:

:required - boolean, sets whether existence of confirmation parameter is required for addition of error. Defaults to false

so since you are setting this to true but not setting the confirmation field in params, you are not getting the error. Try passing a blank confirmation field in your params. Or removing the required option.

**Comment by tuan-karma** [comment]
> Per docs:
> 
> :required - boolean, sets whether existence of confirmation parameter is required for addition of error. Defaults to false
> 
> so since you are setting this to true but not setting the confirmation field in params, you are not getting the error. Try passing a blank confirmation field in your params. Or removing the required option.

Thank @wojtekmach for your quick reply. 
If I pass a blank confirmation field or `password_confirmation: nil`, the errors will always be `{"does not match confirmation", [validation: :confirmation]}`.  So that, the `:required` option is useless. If this options is never used why did you put it in the function?

**Comment by wojtekmach** [comment]
> So that, the :required option is useless. If this options is never used why did you put it in the function?

First of all, that's a bit harsh. :) second of all, here's the rationale: https://github.com/elixir-ecto/ecto/issues/1450.

> In my opinions, "can't be blank" is different from "does not match" errors.

Agreed. Currently you'd only get the "can't be blank" if you have required: true but don't set the field in your params. If you set it, even to `nil`, you'd indeed get "does not match confirmation". Unfortunately you can't `|> validate_required(:password_confirmation)` because it's not a virtual field. It's probably not trivial to change things but if you have a proposal and would like to work on it, let us know.
