### ISSUE TITLE
Multi tenancy app not working with cte queries

### ISSUE THREAD

**Issue by alexcassol** [elixir-ecto/ecto#3387]
### Environment

* Elixir version (elixir -v): **Elixir 1.10.4 (compiled with Erlang/OTP 23)**
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): **PostgreSQL 10.14**
* Ecto version (mix deps): **3.4.6**
* Database adapter and version (mix deps): **postgrex 0.15.5**
* Operating system: **Fedora 32 (Workstation Edition)**

### Current behavior
I have a multi tenancy app that uses recursive queries. 

The problem is that when I give a prefix to the query through `Repo.all(prefix: "tenant_x")`, all the tables and the CTE query uses the prefix.

**Example:**
```elixir
category_tree_initial_query =
  Category
  |> where([c], is_nil(c.parent_id))

category_tree_recursion_query =
  Category
  |> join(:inner, [c], ct in "category_tree", on: c.parent_id == ct.id)

category_tree_query =
  category_tree_initial_query
  |> union_all(^category_tree_recursion_query)

{"category_tree", Category}
|> recursive_ctes(true)
|> with_cte("category_tree", as: ^category_tree_query)
|> select([c], c)
|> Repo.all(prefix: "tenant_x")

```
This SQL is generated:

```sql
WITH RECURSIVE "category_tree" AS (

    SELECT * 
    FROM "tenant_x"."categories" 
    WHERE c.parent_id IS NULL

    UNION ALL (
       SELECT * 
        FROM "tenant_x"."categories" AS c 
        INNER JOIN "tenant_x"."category_tree" AS ct ON c.parent_id == ct.id)
)
SELECT *
FROM "tenant_x"."category_tree" 

```
CTE queries shouldn't have the prefix.

### Expected behavior

I expected that prefix is used only in tables, not CTE query.

```sql
WITH RECURSIVE "category_tree" AS (

    SELECT * 
    FROM "tenant_x"."categories" 
    WHERE c.parent_id IS NULL

    UNION ALL (
       SELECT * 
        FROM "tenant_x"."categories" AS c 
        INNER JOIN "category_tree" AS ct ON c.parent_id == ct.id)
)
SELECT *
FROM "category_tree" 

```

**Comment by josevalim** [comment]
This is by design. You can change this by explicitly setting a prefix in the cte query:

    |> with_cte("category_tree", as: ^%{category_tree_query | prefix: "another one"})

**Comment by alexcassol** [comment]
Ok, I did it that way, but maybe I missing something.

```elixir

{"category_tree", Category}
|> recursive_ctes(true)
|> with_cte("category_tree", as: ^%{category_tree_query | prefix: "tenant_x"})
|> select([c], c)
|> Repo.all()

```

And the result...

```sql
WITH RECURSIVE "category_tree" AS (

    SELECT * 
    FROM "tenant_x"."categories" 
    WHERE c.parent_id IS NULL

    UNION ALL (
       SELECT * 
        FROM "tenant_x"."categories" AS c 
        INNER JOIN "tenant_x"."category_tree" AS ct ON c.parent_id == ct.id)
)
SELECT *
FROM "category_tree" 

```
Note that INNER JOIN with CTE query is still using the prefix: 
`INNER JOIN "tenant_x"."category_tree" AS ct ON c.parent_id == ct.id)`

**Comment by egeersoz** [comment]
I know this is an old issue but it would be nice if it was clearly documented along with some realistic examples.

**Comment by greg-rychlewski** [comment]
@egeersoz We're happy to augment the docs or to accept PR's augmenting them, but it is not always obvious what is not clear to others because we work with the codebase so often that most things are intuitive.

For example, we have [a section here in the docs](https://github.com/elixir-ecto/ecto/issues/3387#issuecomment-1933114763) that walks through the cases. A good first step would be to let us know where you feel it is not clear or what kind of examples are missing. I'm actually surprised multiple people thumbs downed Jose without even engaging with him. It help improve things.

**Comment by josevalim** [comment]
The thumbs down may actually be because I was just plain wrong? My suggestion doesn’t solve the issue it seems, instead, we need a way to specify the from (the query source) without a prefix but I am not sure if it is possible. Perhaps we need to support prefix: false or something?

**Comment by greg-rychlewski** [comment]
I think `prefix: false` is the only way. Probably we need it for regular queries too right? Like this

```elixir
Repo.all(from(p in Post, prefix: false, join: c in Comment, join: s in Something), prefix: "prefix")
```

**Comment by josevalim** [comment]
Yes, exactly, but hopefully it does not require massive changes to Ecto.

**Comment by greg-rychlewski** [comment]
Do you think we should allow `false` at the query level as well? I was thinking yes so entire subqueries/ctes can ignore the prefix while the rest of the query doesn't.

**Comment by josevalim** [comment]
Yeah, I think we have to :(

**Comment by egeersoz** [comment]
Thank you very much for the replies. Before I explain why I gave a thumbs down, I want to apologize if my below post comes across as harsh or rude. That's not my intention. I'm very grateful to everyone in the Elixir community and especially to José and other contributors and maintainers for all their hard work over the years. But, specifically responding to @greg-rychlewski's `I'm actually surprised multiple people thumbs downed José without even engaging with him. Doing that doesn't help improve things` comment:

The first reason for my thumb down vote is that José said "this is by design" but didn't actually explain why. So it came across as quite terse, almost dismissive, especially since he immediately closed the issue afterwards (without even waiting for confirmation from the issue reporter that his suggestion did in fact address their problem). Sorry, but this is a huge pet peeve of mine when open source devs/maintainers do that so seeing it done soured my mood instantly and I didn't feel like engaging further. IMHO, if the original reporter is putting in all that effort to provide example code and describe the expected behavior vs. the result they are seeing, it would be a matter of simple fairness to match that effort with equivalent effort when providing an answer. Not saying every essay should be responded to with an essay, but even something like testing a suggestion to confirm it works before posting it would go a long way to prevent other readers from going down the wrong path (or prefacing it with "I haven't tested this, but..." so that the lack of confidence in the suggestion is clear).

Second, as José also realized, his suggestion didn't actually work. To make matters worse, due to the lack of elaboration in the response itself and also the sparsity of the docs, it wasn't immediately clear to me if it was his suggestion that was wrong, or if I was implementing it incorrectly. After thinking about it, I decided the first possibility was extremely unlikely, simply due to the sheer difference between his level of experience and knowledge vs. mine. So I ended up spending several hours fiddling with my code, googling stuff and trying to put together various bits and pieces I found that might be relevant to the issue. I got so desperate at one point that I even asked ChatGPT (which of course gave a garbage answer). I eventually gave up and went with another, much less efficient strategy, but also came back to this issue to request more exhaustive documentation and examples on this particular use case with prefixes and recursive CTEs.

For posterity, below is what I was working with. I'm trying to count the `catalog_items` in each `category`, with the caveat that the item_counts of top level categories must also include those of their subcategories. For example, there may be 50 items in the Flowers category at the top level, 20 in the Flowers > Roses subcategory and 10 in the Flowers > Daisies subcategory, then the `item_count` of the Flowers category should be 80. This is a very common use case for things like online storefronts.

```
category_tree_initial_query =
  Category
  |> where([c], is_nil(c.parent_category_id))

category_tree_recursion_query =
  Category
  |> join(:inner, [c], ct in "category_tree", on: c.parent_category_id == ct.id)

category_tree_query =
  category_tree_initial_query
  |> union_all(^category_tree_recursion_query)

from(cte in {"category_tree", Category}, prefix: nil)
|> recursive_ctes(true)
|> with_cte("category_tree", as: ^category_tree_query)
|> join(:left, [c], ci in assoc(c, :catalog_items))
|> group_by([c], c.id)
|> select([c, ci], %{c | item_count: count(ci.id)})
|> Repo.all(prefix: "my_tenant_prefix")
```
This generates the following SQL query:
```
WITH RECURSIVE "category_tree" AS (
  SELECT sc0.id AS id, 
         sc0.name AS name, 
         sc0.parent_category_id AS parent_category_id, 
         sc0.inserted_at AS inserted_at, 
         sc0.updated_at AS updated_at 
  FROM my_tenant_prefix.categories AS sc0 
  WHERE (sc0.parent_category_id IS NULL) 
  UNION ALL (
    SELECT c0.id, c0.name, c0.parent_category_id, c0.inserted_at, c0.updated_at 
    FROM my_tenant_prefix.categories AS c0 
    INNER JOIN my_tenant_prefix.category_tree AS c1 ON c0.parent_category_id = c1.id
  )
) 
SELECT c0.id, c0.name, c0.parent_category_id, c0.inserted_at, c0.updated_at, count(c1.id) 
FROM my_tenant_prefix.category_tree AS c0 
LEFT OUTER JOIN my_tenant_prefix.items AS c1 ON c1.category_id = c0.id 
GROUP BY c0.id
```

Which results in `(Postgrex.Error) ERROR 42P01 (undefined_table) relation "my_tenant_prefix.category_tree" does not exist`.

After exhausting all my options, I ended up writing a script to pre-calculate the path of each node by concatenating the ids of parent nodes (e.g. "1-2-5" where 1 would be the id of the top node and 5 would be id of the child node at the bottom and so on). After storing this in a `full_path` column, I can do this:

```
from cat in Category,
where: is_nil(cat.parent_category_id),
left_join: cat2 in Category, on: fragment("? ILIKE CONCAT(?, '%')", cat2.full_path, cat.full_path),
left_join: ci in CatalogItem, on: ci.category_id == cat2.id,
select: [:id, :name, :full_path],
select_merge: %{
  item_count: count(ci.id, :distinct) # I had to add `item_count` as a virtual field to the Category schema
},
group_by: [cat.id, cat.name, cat.full_path]
```
Which itself is simpler as a query, but introduces a lot of complexity to the code base, as the paths of child nodes now need to be recalculated each time a parent node is deleted, moved or added. I believe a recursive CTE is the optimal way to solve this issue so hopefully it can be done in Ecto without resorting to raw SQL.

Again, apologies if I sound frustrated! Just wanted to provide some context for my earlier lack of proper etiquette. I sincerely appreciate that the issue has been reopened and potential solutions are being discussed. Thank you.

**Comment by josevalim** [comment]
Thank you @egeersoz for the feedback. You didn’t sound frustrated at all. ❤️

I do agree my response was poor. I guess it happens to everyone. Whenever you find a response from me that is too concise, feel free to ask for more context. At least I hope this discussion shows I am happy to right some wrongs. :)

**Comment by josevalim** [comment]
Thank you @egeersoz for the feedback. You didn’t sound frustrated at all. ❤️

I do agree my response was poor. I apologize. Whenever you find a response from me that is too concise, feel free to ask for more context. At least I hope this discussion shows we are happy to right some wrongs. :)

**Comment by greg-rychlewski** [comment]
@josevalim Since `%Ecto.Query{}` is opaque we can maybe keep it is `{:ok, nil}` all the way to the end of the planner and then get rid of the tuple at the end That might make it a nicer API so that there aren't two ways to explicitly ask for no prefix. 

But if we do that then everywhere in our code we have to get rid of stuff like this `%{query | prefix: new_prefix}` and use the `attach_prefix` function to ensure the `{:ok, prefix}` format is being adhered to. Or just break if one of us forgets to use an ok tuple when doing `%{query | prefix: new_prefix}`. Do you think that would be a deal breaker?

**Comment by josevalim** [comment]
What if we go for another approach? What if we automatically track CTEs when emitting the query and we do not the prefix if the CTE name matches the table name?

**Comment by greg-rychlewski** [comment]
I think that probably works for CTEs but I believe some other "issues" couldn't be fixed. For example I think these would still suffer a similar issue:

```elixir
sub_query = from p in Post, prefix: nil

from c in Comment, join: s in subquery(sub_query)
|> Repo.all(prefix: "not_nil")
```

```elixir
from p in Post, join: c in Comment, prefix: nil
|> Repo.all(prefix: "not_nil")
```

**Comment by greg-rychlewski** [comment]
I think combinations also have a similar issue where they inherit the prefix from the parent query, which inherits from the repo opt.

**Comment by josevalim** [comment]
@greg-rychlewski I am not worried about those use cases because you can always default to the default prefix, such as public (PG) or the database name (MySQL). The issue with CTEs is that there is no such option, which is why we are trying to make `prefix: nil` work, but I am assuming it is not easy.

**Comment by greg-rychlewski** [comment]
Oh my mind was completely somewhere else. You can do something like this

```elixir
cte_query = from(...) |> put_query_prefix("other")

query =
  from(cte in {"schema", Schema}, prefix: "public")
  |> with_cte("tree", as: ^cte_query)
  |> select(...)
```

Are you trying to solve the case when the repo opt is specified and it must bypass the parent query and make its way down to the CTE query? Like this

```elixir
cte_query = from(...) 

query =
  from(cte in {"schema", Schema}, prefix: "public")
  |> with_cte("tree", as: ^cte_query)
  |> select(...)
  |> Repo.all(prefix: "other")
```

I think in that case combinations have the same issue because they will take the "resolved" parent query prefix and use that instead of the repo opt.

**Comment by greg-rychlewski** [comment]
Sorry I get it now. CTEs aren't tables so they can't be prefixed.

**Comment by greg-rychlewski** [comment]
This is pretty rough. Because you are technically allowed to name your CTE the same name as a real table.  This will work as long as you have a `posts` table in your `public` schema:

```elixir
TestRepo.insert!(%Post{title: "first"})

"posts"
|> with_cte("posts", as: ^from(c in Comment))
|> select([p], p.title)
|> TestRepo.all(prefix: "public")
```

So I think you need to be explicit about wanting no prefix rather than inferring from the name alone. And then you get into things like why does `prefix: nil` work for CTEs but nothing else.

**Comment by josevalim** [comment]
But in your example above the CTE is never used, which is the issue at hand, so I think discarding the prefix outside the CTEs is desired?

**Comment by greg-rychlewski** [comment]
Sorry I was being lazy creating the example. You could also have a situation where someone is not doing a good job naming things and joins the CTE onto a table with the same name in another schema. i.e you have something like this

```elixir
"posts"
  |> with_cte("posts", as: ^from(p in "posts", prefix: "prefix1", where: p.title == ^"something", select: [:id, :title]))
  |> join(:inner, [p1], p2 in "posts", on: p1.id == p2.id)
  |> select([p1, p2], {p1.title, p2.title})
  |> TestRepo.all(prefix: "prefix2")
```

Then basically the user has no way to say I want the table `posts` vs I want the CTE `posts`. We either keep the prefix in both cases (today's behaviour) or ignore both.

**Comment by greg-rychlewski** [comment]
Apologies, I'm not sure I am picture your suggestion properly. Do you mean to ignore the repo prefix and the query prefix and only keep the from/join prefixes when `with_cte` is used?

**Comment by josevalim** [comment]
Yes. If the source name matches the name of a CTE, we ignore the repo/query prefix. Except if the name is inside a particular CTE itself.

**Comment by greg-rychlewski** [comment]
Yeah that seems like a really good approach. Basically we assume they want the CTE unless they say otherwise. That makes more sense than the reverse to me. I'll try it out.
