### ISSUE TITLE
Ecto.Enum.values/2 raises when field is virtual

### ISSUE THREAD

**Issue by aptinio** [elixir-ecto/ecto#3451]
### Environment

* Elixir version (elixir -v): Elixir 1.11.1 (compiled with Erlang/OTP 23)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 12.4
* Ecto version (mix deps): 3.5.3
* Database adapter and version (mix deps): postgrex 0.15.7
* Operating system: Linux

### Current behavior

```elixir
defmodule MySchema do
  use Ecto.Schema

  schema "my_schema" do
    field :virtual_enum_field, Ecto.Enum, values: [:foo, :bar], virtual: true
  end
end
```

```
iex(1)> Ecto.Enum.values(MySchema, :virtual_enum_field)                          
** (ArgumentError) virtual_enum_field is not an Ecto.Enum field
    (ecto 3.5.3) lib/ecto/enum.ex:105: Ecto.Enum.values/2
```

### Expected behavior

```
iex(1)> Ecto.Enum.values(MySchema, :virtual_enum_field)                          
[:foo, :bar]
```

**Comment by Eiji7** [comment]
This happens because:
1. `virtual` field does not appends value to accumulate attribute `@ecto_fields`
2. `__schema__/2` is defined for all values of `@ecto_fields`
3. `__schema__/2` have fallback clause to `nil` in case anything else (even not existing field name) is passed
4. `Ecto.Enum.values/2` function `raises` for `nil` result

For reference:
1. https://github.com/elixir-ecto/ecto/blob/a4b21acd20bf3826300cc34186b98321ceb1006b/lib/ecto/schema.ex#L1801-L1846
2. https://github.com/elixir-ecto/ecto/blob/a4b21acd20bf3826300cc34186b98321ceb1006b/lib/ecto/schema.ex#L556-L606
3. https://github.com/elixir-ecto/ecto/blob/a4b21acd20bf3826300cc34186b98321ceb1006b/lib/ecto/schema.ex#L2019-L2024
4. https://github.com/elixir-ecto/ecto/blob/a4b21acd20bf3826300cc34186b98321ceb1006b/lib/ecto/enum.ex#L97-L107
