### ISSUE TITLE
Cannot use type/2 with interval and search functions

### ISSUE THREAD

**Issue by fuelen** [elixir-ecto/ecto#3495]
### Environment

* Elixir version (elixir -v): 1.11.2
* Ecto version (mix deps): 3.5.5

### Current behavior
```elixir
Call |> select([calls], %{end_date: type(datetime_add(calls.datetime, calls.duration, "minute"), :date)})
** (Ecto.Query.CompileError) the first argument of type/2 must be one of:

  * interpolations, such as ^value
  * fields, such as p.foo or field(p)
  * fragments, such fragment("foo(?)", value)
  * an arithmetic expression (+, -, *, /)
  * an aggregation or window expression (avg, count, min, max, sum, over, filter)

Got: datetime_add(calls.datetime, calls.duration, "minute")

    (ecto 3.5.5) expanding macro: Ecto.Query.select/3
    iex:68: (file)
    (elixir 1.11.2) expanding macro: Kernel.|>/2
    iex:68: (file)
```
`type(like(table.text_field, "text"), :string)` also fails to compile with the same error.
Current workaround is to write such expressions as `type(fragment("(?)", <call_unsupported_function>), :some_type)`

### Expected behavior
Compile query.

**Comment by josevalim** [comment]
Yes, `type` is restricted on purpose because it needs to understand its arguments to emit the proper code. For fragments we make certain assumptions, which seem to work for your example, but are not generally true for all expressions, so we can't simply allow anything.

In your case, since you actually want to cast at the database level, that's what I would do `fragment("(?)::date", <call_unsupported_function>)`.
