### ISSUE TITLE
mix ecto.* commands should produce a much more descriptive message for the end-user

### ISSUE THREAD

**Issue by conradwt** [elixir-ecto/ecto#3737]
### Environment

* Elixir version (elixir -v):  1.13.0-dev (004c2ef)
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): PostgreSQL 13.3
* Ecto version (mix deps):  3.7.1
* Database adapter and version (mix deps):  postgrex 0.15.10
* Operating system: macOS 11.5.2

### Current behavior

```bash
➜ mix ecto.create          
The database for Phoenix160app.Repo has already been created
```

### Expected behavior

```bash
➜ mix ecto.create          
The database, "myapp_dev", for Phoenix160app.Repo has already been created
```

**Comment by v0idpwn** [comment]
ecto.create/ecto.drop tasks are implemented on Ecto, but it delegates to adapter. "database_name" is adapter dependent and message building/printing is done on Ecto, so we can't rely on this config existing, because some adapter may not use it.

@josevalim if you have some suggestion on how we could work around this please let me know and I can work on it :)

**Comment by josevalim** [comment]
Right, to give an example, your database can be a "ets table" or even a GitHub repo. So there is no particular database name we can look at. It can be anything. The best we can do is include the environment but is that helpful?

    The dev database for Phoenix160app.Repo has already been created

**Comment by conradwt** [comment]
@josevalim Yes, that's not as helpful as I would like because I would like to know the name of the database here.  Anyway, thanks for the clarification on what's happening and I appreciate it.  This issue can be closed.
