### ISSUE TITLE
Cast Fragment to virtual field type

### ISSUE THREAD

**Issue by HangingClowns** [elixir-ecto/ecto#3767]
### Precheck

* Informed by Jose to post on here

### Environment

* Elixir version (elixir -v): 1.12.1
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): Postgres 14
* Ecto version (mix deps): 3.6.1
* Database adapter and version (mix deps):
* Operating system: Mac OS

### Current behavior

'm stuck at an issue. I have a virtual field that I setup as an Ecto.Enum, and I'm trying to make that value into an atom. I have a "friend_status" field, and if there's a friend request that's not been accepted, then it's pending, if it's accepted, then they are friends, and if no field, then they are basically strangers.

I have my case statement working great in a fragment, but it's returning the strings instead of loading the atom. Here's a sample:
```elixir
from(
...
select: %{ u | friend_status: fragment("CASE WHEN ? THEN 'stranger' ELSE 'pending' END", is_nil(f.id))}
)
```

I tried using Ecto.Query.API.type/2 function, but I'm not sure what to put it as, since when I tried just the column name, it doesn't work, it returns an error saying it's a virtual field.

Is there a way to make this work?

### Expected behavior

Somehow, I should be able to cast the string into an atom because it's using Ecto.Enum as the type.

**Comment by v0idpwn** [comment]
Using type/2 doesn't work because we don't have the types for virtual fields stored. 

We could virtually support receiving parameterized types (as we allow base types and custom types) on type/2, but it probably wouldn't be really useful as the internal parameters are not accessible to user and are defined in compilation time, so building the parameterized type would be required every time (i.e: `type(input, Ecto.Enum.init(values: @enum_values)`.

ATM I don't see many options other than casting by hand.

**Comment by v0idpwn** [comment]
@HangingClowns you should be able to use type/2 with your field name on master. Please let me know if you have any issue.
