### ISSUE TITLE
Redacted attributes in query logs

### ISSUE THREAD

**Issue by kodnin** [elixir-ecto/ecto#3792]
### Environment

* Elixir version (elixir -v): 1.13.0
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): SQLite3
* Ecto version (mix deps): 3.6
* Database adapter and version (mix deps): `ecto_sqlite3`
* Operating system: Alpine

### Current behavior

I'm unsure whether this is an issue. In a Phoenix app the user's password column is redacted. In the Phoenix server's parameters log it is nicely `[FILTERED]`, but in the query log we see the value of `"123456"`.

```elixir
  schema "users" do
    field :email, :string
    field :password, :string, redact: true

    timestamps()
  end
```

```elixir
[info] Sent 200 in 32ms
[info] POST /users
[debug] Processing with Test123Web.UserController.create/2
  Parameters: %{"_csrf_token" => "VmEKG3xoAT0UUXYNG2QJBBcPKQd_cTUmcSKc803Vs77fR6lac6QC00FA", "user" => %{"email" => "a@b.com", "password" => "[FILTERED]"}}
  Pipelines: [:browser]
[debug] QUERY OK db=15.0ms idle=1434.5ms
INSERT INTO "users" ("email","password","inserted_at","updated_at") VALUES (?,?,?,?) RETURNING "id" ["a@b.com", "123456", "2021-12-06T23:12:56", "2021-12-06T23:12:56"]
```

### Expected behavior

The value for the user's password is also redacted in the query log.

**Comment by v0idpwn** [comment]
The problem is that the query is run and logged by the adapter.

The adapters don't know much about the query (for them, "123456" is just a term in a list of params). We can't really change the shape of params because it would introduce a compatibility break. Another alternative would be passing this information as metadata, but I think that, if this is possible, it probably would introduce significant overhead. So at the moment, I don't see a solution.

My guess is that logging shouldn't be used for all queries in production.

**Comment by josevalim** [comment]
You can disable logging per query but I would say that sensitive data should not be going to the database decrypted because there are bouncers and the database itself that may still log the query (plus anyone with read access).

for passwords and personal identification information, you want to make sure it is encrypted. See projects like ecto_cloak to help here. :)
