### ISSUE TITLE
Updating a record in a Repo transaction failure

### ISSUE THREAD

**Issue by rafaeliga** [elixir-ecto/ecto#3944]
### Elixir version

Elixir 1.13.1 (compiled with Erlang/OTP 24)

### Database and Version

PostgreSQL 14

### Ecto Versions

ecto 3.7.1, ecto_sql 3.7.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.15.13

### Current behavior

1. Create a Repo transaction
2. First insert fail
3. Then on :error, failure, try to update other table

Repo/script to test: https://github.com/rafaeliga/ecto-transaction-flow-sample/blob/master/script.exs#L60

Stacktrace:

** (Postgrex.Error) ERROR 25P02 (in_failed_sql_transaction) current transaction is aborted, commands ignored until end of transaction block

    query: UPDATE "configs" SET "lines" = $1, "updated_at" = $2 WHERE "id" = $3
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.8.4) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
    (ecto 3.8.4) lib/ecto/repo/schema.ex:451: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
    (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:1222: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection 2.4.2) lib/db_connection.ex:1562: DBConnection.run_transaction/4

### Expected behavior

Expected behavior would be to be able to update the config table in the :error/failure.

**Comment by josevalim** [comment]
There is nothing we can do: the **database** does not let you do anything in a transaction where a previous operation failed. You can move the error handling outside of the transaction if you prefer and match on the transction error instead.

**Comment by rafaeliga** [comment]
@josevalim The [documentation](https://hexdocs.pm/ecto/Ecto.Repo.html#c:transaction/2) says "if an unhandled error occurs the transaction will be rolled back [...]" and the examples supporting the explanation only show unsafe functions that raise exceptions. Right after that it says "If no error occurred the transaction will be committed when the function returns". If handled errors also rollback the transaction, should we update the docs and examples to better explain that?

**Comment by thiagomajesk** [comment]
Hi @josevalim! I think there's some information missing on our part. 
So, could you help us understand what's happening it a little better? Here it goes...

The overall intention is to update a given "tag" after a "post" is inserted. However, if the "tag" update fails, we want to roll back the whole thing. The "tag" in this example, acts like a "logging mechanism", so if it's not possible to log the information whether it succeeded or not, we don't really care about the "post".

```elixir
Repo.transaction(fn repo ->
  # no 'exception' here, just a handled error 
  # (if this returns {:error, changeset} does the transaction rolls back?)
  case repo.insert(changeset) do
    {:ok, post} ->
      tag
      |> Ecto.Changeset.change(%{name: "success"})
      |> repo.update!()
    {:error, changeset} ->       
      tag
      |> Ecto.Changeset.change(%{name: "failure"})
      |> repo.update!()
    end
end)
```

Ok, this was so we can get on the same page of what we are actually trying to achieve. Now to the hairy bits...

When I read _"if an unhandled error occurs the transaction will be rolled back"_, I understand that "unhandled error" is referring to an application exception (aka `raise`). Since we are using `repo.insert` (which does not raise), I assumed the transaction should not roll back. It seems to me that you have confirmed this in your last comment, that we should understand "errors" as "exceptions".

In the following sentence, we have _"If no error occurred the transaction will be committed when the function returns"_. Ok, so if "error" in this case should also be understood as an exception, it reinforces our understanding that since there are no exceptions being raised, the transaction shouldn't be rolling back - making it more confusing.

After conducting some tests, we could observe that `repo.update!` only fails because of `repo.insert`, however, I'm not sure I have all the information to connect the dots of what's happening here.

I hope I could explain our minds a little better... Do you think you can help us make sense of how this is supposed to work? I'm sure there's something here that we are not understanding and it's inducing this mismatch of information between what we are reading in the docs and what's actually happening. We'll gladly help improve the docs after we understand what's actually expected.

Thanks in advance. Cheers!

**Comment by wojtekmach** [comment]
Consider asking these questions on elixir forum and such where wider group of people can help out as well as see the responses. And when it is clear, we will happily accept a PR with docs improvements.

**Comment by thiagomajesk** [comment]
Hi @wojtekmach! Thanks for the consideration but this is not exactly a question to be made in the forums. 
I'm trying to make sense of @josevalim response to see what is exactly the action to be taken here. Since we already have some context in this thread, I think it would be counterproductive to go to the forums and ask about what someone else meant in this discussion.

In other words, since we agreed there's something to be improved in the docs, we are trying to get better context to understand what that thing is.

**Comment by josevalim** [comment]
@wojtekmach meant that it will help to make sense about this on the forums, with help of others, because there is a lot of context and our hands are pretty tied. :)

**Comment by josevalim** [comment]
I pushed some initial docs expanding this but I recommend further discussion and clarifications on the forum. :) PRs for fixes also welcome.

**Comment by thiagomajesk** [comment]
Hey, @josevalim thanks for the intention but this new "Aborted transactions" section just opened a whole new can of worms. Since I'm feeling a little bit gaslit from this interaction, I'll wait to see if someone in the forums will help us put the pieces together with the information we already have and we'll get back to it.

**Comment by v0idpwn** [comment]
To recover the transaction from these invalid states, you may use savepoints.
