### ISSUE TITLE
Changeset preload required for unchanged relations

### ISSUE THREAD

**Issue by zoten** [elixir-ecto/ecto#4002]
### Elixir version

1.13.4

### Database and Version

SQLite 3, MySQL 8

### Ecto Versions

3.8.4

### Database Adapter and Versions (postgrex, myxql, etc)

ecto_sqlite3 0.8.1, myxql 0.6.2

### Current behavior

Hi! Thanks for the wonderful work :pray: 
I'm seeing a strange behaviour very similar to [1761](https://github.com/elixir-ecto/ecto/issues/1761) on a different use case.
I replicated it in [this poc project](https://github.com/zoten/ecto_bug_preload) but should be as easy as

 - create a schema with `has_many` relation (classic Author -> Post)
 - insert a record
 - update changeset
 - `Repo.insert(on_conflict: :replace_all)` or `Repo.insert(on_conflict: {:replace_all_except, :posts})`

Same behaviour happens with mysql and sqlite, and I have small doubts it is DB-agnostic since it seems to be a changeset/repo validation bug

*Error*

```
** (RuntimeError) attempting to cast or change association `posts` from `EctoBug.Schema.Author` that was not loaded. Please preload your associations before manipulating them through changesets
```

### Expected behavior

Should simply update changed fields and leave unchanged relations as they are

If there is any hint to start working on a patch I'll be happy to put some effort. I made up the poc since I was unsure on where to put unit tests, sorry for the burden of a new project  to check out :pray: 

Edit 1: It is worth noting that using `replace_all_except: [:id]` as by documentation does **not** work, ending up with the same result.

Edit 2: I added some cases in the repository (triggered by passing `:one` (default), `:two`, `:three` or `:four` as argument) to show different cases with different outcomes, also playing with non-pk constraint, which should be the default case when this happens

**Comment by greg-rychlewski** [comment]
Hi,

Thank you for your report. If I understand your example correctly, you are trying to upsert a struct that has its association populated with a `%Ecto.Association.NotLoaded{}` struct. 

Since you are doing an upsert (insert or update) Ecto will treat all the struct values as possible changes. So when it sees the association field populated with `%Ecto.Association.NotLoaded{}` it raises because that value can't possibly be sent to the database. 

The `:replace_all` and `{:replace_all_except, things}` options you are specifying happens at the database level and are part of the query that is generated. If the database detects a conflict it will only update the fields you specified. But before we get to the database we have no way of knowing if it will be an insert or an update so all values have to be considered changes.

Hope this makes sense. Let me know.

**Comment by josevalim** [comment]
Great analysis @greg-rychlewski!

I think we ignore not loaded associations on insert and update... so perhaps it also makes sense to ignore them on upserts?

**Comment by greg-rychlewski** [comment]
Yeah that makes sense from my perspective. My only hesitation is [this comment makes it seem intentiona](https://github.com/elixir-ecto/ecto/blame/master/lib/ecto/changeset/relation.ex#L74)l, so I'm a bit worried I'm not seeing something.

**Comment by josevalim** [comment]
I need to take a deeper look then. That code is definitely correct... I am wondering if we would bypass `load!` for that association somehow, because `insert`/`update` is certainly bypassing it?

**Comment by greg-rychlewski** [comment]
@zoten Thanks for the report and good find! It's fixed on master now.

**Comment by zoten** [comment]
Thanks for the super-fast feedback and effort :pray:
