### ISSUE TITLE
`validate_required/3` doesn't catch certain zero-width UTF-8 characters

### ISSUE THREAD

**Issue by sodapopcan** [elixir-ecto/ecto#4087]
### Elixir version

1.14.2

### Database and Version

14.6

### Ecto Versions

3.9.4

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

As a buddy of mine discovered in my app, certain zero-width or blank unicode characters aren't caught by `validate_required/3`.  For example, [zero width space](https://unicode-explorer.com/c/200B) and [braille blank space](https://unicode-explorer.com/c/2800).  These seem to end up in the db as zero-width though I'm not sure how to test that but when fetched with Ecto, the fields come back as `field: ""`.

### Expected behavior

I'm not sure if this is really a bug but I found it a bit surprising.  I was thinking maybe this could affect accessibility but I can't really think how as a bunch of blank characters are a bunch of blank characters no matter how you slice 'em.  At the very least the documentation could be updated to point this out.  I would be happy to do the work either way.

**Comment by josevalim** [comment]
`validate_required` trims whitespace but zero-width joiners, braille blank, etc are not white space. I am not sure if we should update the docs because the whitespace mention is clear.

Unfortunately Unicode doesn't provide a reference for what are invisible characters, so there is nothing we could add. Perhaps because it is not a notion users should be worried about (after all invisible characters are only part of non-readable text that can be written).

Therefore, the best way to think about this is that `validate_required` helps prevent users who accidentally left an input blank, or an API that forgot a field, but it doesn't mean the input is actually "representable".

**Comment by sodapopcan** [comment]
I never thought of it as "make sure users didn't accidentally leave something blank" but with that line of thinking, it does make sense not to worry about this.  Thanks for the answer!
