### ISSUE TITLE
Discussion: validate_required_or(_xor)

### ISSUE THREAD

**Issue by greg-rychlewski** [elixir-ecto/ecto#4109]
### Elixir version

All

### Database and Version

All

### Ecto Versions

3.10-dev

### Database Adapter and Versions (postgrex, myxql, etc)

All

### Current behavior

Functions don't exist.

### Expected behavior

I have a feeling this came up before but I couldn't find any previous discussion. Apologies if I missed it.

The idea would be to have 2 new functions in `Ecto.Changeset`:

- `validate_required_or/3`
- `validate_required_xor/3`

They would both take a list of fields. The former would validate that at least one of the fields is present. The latter that exactly one of the fields is present. 

I came across this when validating API query parameters and didn't see anything in the current API to do something like it. It's not terrible to roll my own solution either so not a big deal either way.

**Comment by v0idpwn** [comment]
validate_required/3 accepts options. It could be an alternative to add options for such behaviours. Though maybe its not a good idea because it changes the semantics of the function.

**Comment by wojtekmach** [comment]
Yeah I've needed something like this myself a few times. Having it out of the box would be a nice addition.

I'm not sure about implementing it though. We keep required validations as `changeset.required`, not `changeset.validations` like all the other ones,

```elixir
iex> Ecto.Changeset.cast({%{}, %{name: :string}}, %{}, ~w(name)a) |> Ecto.Changeset.validate_required(:name) |> Map.take([:required, :validations])
%{required: [:name], validations: []}
```

and so not sure how to represent at-least-one-required and at-most-one-required using the current scheme. I guess if neither at-least-one nor at-most-one is given, we keep the validation in `changeset.errors`, otherwise we add `{:required, at_least_one|at_most_one: true}`?

**Comment by josevalim** [comment]
@greg-rychlewski I agree with both decisions and their rationale.

**Comment by wojtekmach** [comment]
+1 from me too. It will be slightly awkward that regular required validations will be represented differently than new required validations but we cannot reconcile the two and shouldn’t make breaking change and I don’t think it’s a huge deal anyway.
