### ISSUE TITLE
bug in has_one-through scenario: preload not set when combining atom and existing join

### ISSUE THREAD

**Issue by dirkholzapfel** [elixir-ecto/ecto#4112]
### Elixir version

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Database and Version

postgres (PostgreSQL) 14.5

### Ecto Versions

3.10.0-dev

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.16.5

### Current behavior

See failing test case in https://github.com/dirkholzapfel/ecto/tree/bug/preload

A preload is not set when mixing an atom and an existing join in the expression:
```
Repo.one(
        from(c in Comment,
          join: pp in assoc(c, :post_permalink),
          join: u in assoc(pp, :user),
          preload: [post_permalink: {pp, [user: u]}]
        )
      )
--> user is preloaded

Repo.one(
        from(c in Comment,
          join: pp in assoc(c, :post_permalink),
          join: u in assoc(pp, :user),
          preload: [post_permalink: {pp, [:post_comments_authors, user: u]}]
        )
      )
--> user is not preloaded (#Ecto.Association.NotLoaded<association :user is not loaded>)      
```

### Expected behavior

The preload should be set

**Comment by greg-rychlewski** [comment]
Right now it's not possible to mix the 2 types of preloads, the "join" preloads and the "separate query" preloads. You can think of it like this:

1. Your main struct has the "join" preloads added.
2. Now Ecto looks for the "separate query" preloads and puts them on the main struct. These ones don't know about the previous preloads so they are erased.

So you'd have to make them both "separate query" preloads in your case. 

To make the compatible is pretty ugly, I think. You'd have to track all the sub-preloads of the first type and then make the second type aware of them. And you have join_through and that kind of stuff. Maybe the best we can do is make a note in the docs. But I'll see what the others say.

**Comment by dirkholzapfel** [comment]
Thanks @greg-rychlewski, I understand the problem better now ❤️.
I am 👍 on raising an error.

**Comment by greg-rychlewski** [comment]
I apologize I misspoke. The issue I mentioned only affects `through` associations and it is indeed a bug. You can test a non-through association like this in the same situation and it works:

```elixir
post = TestRepo.insert!(%Post{})
    user = TestRepo.insert!(%User{})
    comment = TestRepo.insert!(%Comment{post: post, author_id: user.id})
    TestRepo.insert!(%Permalink{post: post, user: user})

    query =
        from(c in Comment,
          join: a in assoc(c, :author),
          join: p in assoc(a, :permalink),
          preload: [author: {a, [:comments, permalink: p]}]
        )

    [c1] = TestRepo.all(query)
```

In the non-through situation what happens is:

1. The `Permalink` struct is joined into the `Author` struct.
2. The separate query preload puts the `Comment` structs into the `Author` struct from (1). Not a fresh struct like I said before. So `Author` has both preloads just fine.

In the through situation it is more complicated.  Basically what happens is the through associations are preloaded recursively (Comment -> Post -> Permalink -> Post -> Comment -> Author). So it is not starting from the `PostPermalink` struct that already has `User` joined into it.  And those recursive preloads are used to populate the `PostPermalink` struct. This is why the join preload information disappears.

So at least we know where the issue is. I'll work on figuring out the fix.

**Comment by greg-rychlewski** [comment]
@josevalim I'm at a bit of a loss for how to handle this one. I had some ideas but was wondering what you thought.

There is an issue with preloads that are nested inside a `through` association. For example:

```elixir
# post_permalink is through [:post, :permalink]. It already has a nested association `user` preloded
c = %Comment{post_permalink: %Permalink{user: %User{}}|
c = Repo.preload(c, post_permalink: [:some_other_assoc])

# user is not preloaded anymore
%Ecto.Association.NotLoaded{} = c.post_permalink.user
```

The nested association in the `through` association disappears because `through` preloads happen this way:

1. Each individual association in the chain is preloaded like a normal association.
2. The last result from the chain is `put` into the `through` field. Erasing anything else that was there.

Originally I thought we can just keep any preloaded `through` structs and insert them at the right time. But then I ran into some issues:

1. For `one` associations, it can be the case that multiple structs passed into the preload function have the same foreign key for the `through` association but they have different versions of the struct already preloaded. Then it's not clear which one to choose. For example:

```elixir
%Comment{} = c1 = TestRepo.insert!(%Comment{post_id: pid1})
%Comment{} = c2 = TestRepo.insert!(%Comment{post_id: pid1})

%User{id: uid1} = TestRepo.insert!(%User{name: "foo"})
%Permalink{id: lid1} = pl1 = TestRepo.insert!(%Permalink{user_id: uid1, post_id: pid1, url: "1"})

[pl1] = TestRepo.preload([pl1], :user)

c1 = %{c1 | post_permalink: pl1}
c2 = %{c2 | post_permalink: pl1}
TestRepo.preload([c1, c2], post_permalink: [:some_other_assoc])
```

Both `c1` and `c2` have the same `post_permalink` association. So when it's going through the chain of normal associations only one `post` struct will be created. Then you have to pick which `post_permalink` struct to place in there before it preloads `permalink`. In this case they are the same but if they were preloaded at different times they could be different.

2. For `many` associations it has similar issues as `one` but even worse because now the list of preloads can be different.

I am thinking of some options but all of them have a downside:

1. Detect the situations where this might happen and warn the user. I don't like this option too much because it's pretty hard to explain what is happening and it will probably be confusing. Especially because this can also happen through joins. If your first preload is a `join` preload then the next a `separate query` preload.  Also it's not great that we can't support this.
2. Do a separate preload for the `though` association instead of putting the result of the preload chain into it. This isn't so great either because it's an extra query per association and also then it's possible the `though` field is out of sync with the regular association fields. Especially for `many` associations where the size of the list can even be different.

Warning seems like the lesser of 2 evils to me. But I could be missing some other option.

**Comment by josevalim** [comment]
Thank you for the wrap up!

I think there are two different concerns here:

1. Repo.preload typically does not override if the association has already been loaded unless `force: true`, so we could follow the same behaviour here? More concretely, we avoid loading the intermediate steps if the through association has already been loaded

2. For preload coming from the association, we could always set `force: true`, because we can assume that was nothing there (or what was there is either the same or not relevant)?

Would this help?

**Comment by greg-rychlewski** [comment]
> More concretely, we avoid loading the intermediate steps if the through association has already been loaded
This makes sense to me and I think it's the insight I was missing. I'll try down this route and see how it goes.

>For preload coming from the association, we could always set force: true, because we can assume that was nothing there (or what was there is either the same or not relevant)?

I'm not sure if I'm understanding correctly. Do you mean when we are preloading the association inside of a query instead of calling `Repo.preload` directly?

If so I think making it `force: true` would cause an issue. For instance you can preload a `though` association and one of its nested associations through joins. And then if you also have a nested separate query preload we will erase the nested join preload by setting `force: true`.

**Comment by josevalim** [comment]
I meant the preload from an Ecto.Query, so your first comment is correct, and I agree that treating it as `force: true` would then be a bad idea. :)
