### ISSUE TITLE
Using type/2 to cast to :text type returns an error

### ISSUE THREAD

**Issue by eldano** [elixir-ecto/ecto#4389]
### Elixir version

1.16.0

### Database and Version

PostgreSQL 14

### Ecto Versions

3.11.1

### Database Adapter and Versions (postgrex, myxql, etc)

postgrex 0.17.4

### Current behavior

I'm type casting on a join doing something like:

```elixir
response.order_id == type(order.id, :string)
```

Which is converted in postgres to `ON (s0."order_id" = s1."id"::varchar)`. 
I need however, for it to be converted to `ON (s0."order_id" = s1."id"::text)`

Passing `:text` as the second argument of `type/2` is not possible, it raises an error
`(UndefinedFunctionError) function :text.type/0 is undefined (module :text is not available)`

### Expected behavior

I'd expect being able to pass `:text` to `type/2` to emit the correct type in postgres

**Comment by josevalim** [comment]
`type/2` is about Ecto types. If you want to bypass the Ecto type handling, you can use a fragment: `fragment("?::text", column)`.

**Comment by Schultzer** [comment]
I understand closing this due to it being an ecto type, but I think the adapter should cast to text on Postgres. It is the native string type: https://www.postgresql.org/docs/current/datatype-character.html, and there is negligible benefit in varchar and friends unless you explicitly want to constrain the value.

Unless I’m missing something, I feel this would be a good default.

**Comment by josevalim** [comment]
That would be a fundamental change. `type/2` is always about Ecto types. It does not understand _any_ database type.

**Comment by josevalim** [comment]
And `varchar` is how Postgres maps the `:string` type by default in migrations. Maybe `text` is better but we cannot change it without breaking all migrations and Ecto code written in the last decade.

**Comment by Schultzer** [comment]
I think it should be possible to avoid most of this, given the available tools, the formatter, which could help format migrations to use Varchar explicitly for old migrations.

Since a migration always has a timestamp, that could also be used to identify.

For what is worth, I’m not saying I have a solution for these constraints, but I do believe there are ways to mitigate these constraints.

**Comment by Schultzer** [comment]
And it looks like it could be changed on the fly without requiring a lock https://stackoverflow.com/questions/44142966/change-column-type-varchar-to-text-in-postgresql-without-lock-table#44156477
