### ISSUE TITLE
Unnecessary queries on through associations when using Repo preload

### ISSUE THREAD

**Issue by andrew-combs** [elixir-ecto/ecto#4506]
### Elixir version

1.17

### Database and Version

Postgres 16

### Ecto Versions

3.12.2

### Database Adapter and Versions (postgrex, myxql, etc)

0.19.1

### Current behavior

When preloading a `:through` association when the parent struct already has the data, but the intermediate relation does not, calling `Repo.preload` will result in a database query.

Example:

```elixir
defmodule Parent do
  schema "parents" do
    has_one :child, Child
    has_one :grandchild, through: [:child, :grandchild]
  end
end

parent = %Parent{
  grandchild: %GrandChild{loaded: :data},
  child: %Child{
    grandchild: %Ecto.Association.NotLoaded{...}
  }
}

# Results in a query to the database
Repo.preload(parent, [:grandchild])
```

### Expected behavior

When the associated `through` data is already loaded on the parent, the preload should not result in a query to the database.

**Comment by josevalim** [comment]
We don't plan to solve this right now because the data in the struct does not necessarily mirror the data in the database. For example, you could have used a changeset to change the nested data (or vice-versa). Trying to guess if the data is in correct or not will cause more issues.

Since you have "two sources" of the data and you want them to be in sync, my recommendation is either guarantee manually that's the case by forcing preloads or by removing the through association and going parent -> child -> grandchild explicitly.

**Comment by andrew-combs** [comment]
Ah, thinking about it a bit more, the state consistency issue makes sense. Appreciate the quick response ❤️
